### ISSUE TITLE
[Bug] Only the absolute path works for importing contract JSON ABI

### ISSUE THREAD

**Issue by MarcusWentz** [alloy-rs/alloy#1020]
### Component

contract

### What version of Alloy are you on?

0.1.3

### Operating System

Linux

### Describe the bug

From alloy contract example:

https://github.com/alloy-rs/examples/blob/main/examples/contracts/examples/interact_with_abi.rs

```rust
// Codegen from ABI file to interact with the contract.
sol!(
    #[allow(missing_docs)]
    #[sol(rpc)]
    IWETH9,
    "examples/abi/IWETH9.json"
);
```

I get the following error:

```rust
error: failed to canonicalize path <absolute_path>: No such file or directory (os error 2)
  --> src/main.rs:11:5
   |
11 |     "examples/abi/IWETH9.json"
   |   
```

The error goes away when I use the absolute path instead of the relative path.

What might be causing this?

Is there a simple work around to use a relative path?

**Comment by MarcusWentz** [comment]
This is working on my end now (my current directory when running this command is the root of the rust project).

When I run the following command to see my current directory path:
```bash
ls
```
I see the following files:
```
abi  Cargo.lock  Cargo.toml  src  target
```
Updated relative path (I am using WETH9 instead of IWETH9 in this case):
```rust
sol!(
    #[allow(missing_docs)]
    #[sol(rpc)]
    WETH9,  
    "abi/WETH9.json"
);
```

**Comment by DaniPopes** [comment]
relative paths are based in the cargo manifest (Cargo.toml) directory
