### ISSUE TITLE
[Feature] Add 7702 authorization list to rpc tx and receipt types

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1032]
### Component

rpc

### Describe the feature you would like

ref https://github.com/ethereum/execution-apis/issues/561

## TODO

* add `authorizationList: Option<Vec<Authorization>>` as an additional field to rpc Transaction and tx receipt types

https://github.com/alloy-rs/alloy/blob/83343b172585fe4e040fb104b4d1421f58cbf9a2/crates/eips/src/eip7702/auth_list.rs#L8-L19

**Comment by PanGan21** [comment]
Hey @mattsse I did some effort for this in #1051 . Please let me know if something is missing! 🙂

**Comment by onbjerg** [comment]
Closing this as closed by #1051, thanks for the PR:)
