### ISSUE TITLE
[Bug] Deserialize using bincode fails for eip-2930 transactions

### ISSUE THREAD

**Issue by unitezen** [alloy-rs/alloy#1033]
### Component

consensus, eips, genesis

### What version of Alloy are you on?

alloy v0.1.4

### Operating System

Linux

### Describe the bug

Please refer to this context: https://github.com/paradigmxyz/reth/issues/9433

The issue is introduced in https://github.com/alloy-rs/alloy/commit/194f266fae46c1214004d04d4606010c3807b534 and is present from v0.1.3 onwards. It's probably a quirk of bincode, so not sure what the course of action should be or if it should be fixed.

**Comment by mattsse** [comment]
this has been fixed
