### ISSUE TITLE
[Feature] 7702 auth nonce is no longer optional

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1048]
### Component

consensus, eips, genesis

### Describe the feature you would like

converted from list with optional item to regular value

https://github.com/ethereum/EIPs/pull/8677

## TODO
* remove OptionalNonce type

https://github.com/alloy-rs/alloy/blob/8abc6071cbae6e41579c4ee21610d20848ab253c/crates/eips/src/eip7702/auth_list.rs#L22-L23

**Comment by rakita** [comment]
This change should be included in devnet-2, in devnet-1 the previous spec is still valid one.
