### ISSUE TITLE
[Bug] alloy-eips 0.1.5 is breaking revm 11.0

### ISSUE THREAD

**Issue by wtdcode** [alloy-rs/alloy#1060]
### Component

consensus, eips, genesis

### What version of Alloy are you on?

0.1.5

### Operating System

None

### Describe the bug

Reference: https://github.com/bluealloy/revm/pull/1605#issuecomment-2230382383

Can we have a quick makeup release to fix this?

**Comment by wtdcode** [comment]
I need to put these lines to make it work:

```
alloy-eips = { version = "<0.1.5"}
alloy-consensus = {version = "<0.1.5" }
alloy-rpc-types-eth = { version = "<0.1.5" }
```

btw, why doesn't `alloy` advance to `0.1.5`??

**Comment by mattsse** [comment]
release process broke, fixing today
we should do minor instead, yanked all 0.1.5 releases

**Comment by wtdcode** [comment]
> release process broke, fixing today we should do minor instead, yanked all 0.1.5 releases

Thanks for the quick response =).
