### ISSUE TITLE
[Bug] `alloy-consensus` should use `alloy_primitives::Sealable`

### ISSUE THREAD

**Issue by Wollac** [alloy-rs/alloy#1071]
### Component

consensus, eips, genesis

### What version of Alloy are you on?

alloy-consensus v0.2.0

### Operating System

None

### Describe the bug

There are currently two versions of `Sealable`/`Sealed`. One that lives in [alloy-consensus](https://github.com/alloy-rs/alloy/blob/v0.2.0/crates/consensus/src/sealed.rs) and one in [alloy-primitives](https://github.com/alloy-rs/core/blob/v0.7.7/crates/primitives/src/sealed.rs). This should be consolidated and the more general `alloy-primitives` crate used.

**Comment by mattsse** [comment]
thanks for pointing this out, fully agree

@zerosnacks do you want to take this?
