### ISSUE TITLE
[Feature] allow any signature type for tx encoding

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1077]
### Component

consensus, eips, genesis

### Describe the feature you would like

these functions don't require a specific signature generic and can operate on `Signature<S>`

https://github.com/alloy-rs/alloy/blob/067cc464bd1357e745653709db051707b949cc6b/crates/consensus/src/transaction/legacy.rs#L121-L121

https://github.com/alloy-rs/alloy/blob/067cc464bd1357e745653709db051707b949cc6b/crates/consensus/src/transaction/legacy.rs#L107-L109

we can keep the usage in the trait fn for now

https://github.com/alloy-rs/alloy/blob/067cc464bd1357e745653709db051707b949cc6b/crates/consensus/src/transaction/legacy.rs#L253-L253

FYI @leruaa

**Comment by leruaa** [comment]
Thanks, taking this :)

**Comment by mattsse** [comment]
as you already discovered, this needs an alloy-primitives change first

**Comment by leruaa** [comment]
I started the alloy-primitives part: https://github.com/alloy-rs/core/pull/689
