### ISSUE TITLE
[Bug] eip7251 has incorrect consolidation predeploy code

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#1103]
the leading `0x0f5f395ff` needs to be trimmed to match [spec](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7251.md#bytecode) in which the code starts with `sender push20` which is `0x3373`. The current bytecode seems to be some sort of manual trimming error on the [deployment tx code](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7251.md#deployment)?

https://github.com/alloy-rs/alloy/blob/2ce8525d016f3fa9dc9c5a61afe44126a479243f/crates/eips/src/eip7251.rs#L14C66-L14C732

**Comment by onbjerg** [comment]
Yes, this was my bad. I opened up a draft PR to remind myself to correctly trim it, which I will do within the next hour. Unfortunately the devex is super bad for these kind of EIPs, because they don't post the runtime bytecode, only the deployment bytecode, so you manually need to trim it -.-

**Comment by DaniPopes** [comment]
Manually verifying:
- tx input (creation code): `0x61049d5f5561014880600f5f395ff33373fffffffffffffffffffffffffffffffffffffffe146098573615156028575f545f5260205ff35b36606014156101445760115f54600182026001905f5b5f82111560595781019083028483029004916001019190603e565b90939004341061014457600154600101600155600354806004026004013381556001015f35815560010160203581556001016040359055600101600355005b6003546002548082038060011160ac575060015b5f5b81811460f15780607402838201600402600401805490600101805490600101805490600101549260601b84529083601401528260340152906054015260010160ae565b9101809214610103579060025561010e565b90505f6002555f6003555b5f548061049d141561011d57505f5b6001546001828201116101325750505f610138565b01600190035b5f555f6001556074025ff35b5f5ffd`
- outputs: `3373fffffffffffffffffffffffffffffffffffffffe146098573615156028575f545f5260205ff35b36606014156101445760115f54600182026001905f5b5f82111560595781019083028483029004916001019190603e565b90939004341061014457600154600101600155600354806004026004013381556001015f35815560010160203581556001016040359055600101600355005b6003546002548082038060011160ac575060015b5f5b81811460f15780607402838201600402600401805490600101805490600101805490600101549260601b84529083601401528260340152906054015260010160ae565b9101809214610103579060025561010e565b90505f6002555f6003555b5f548061049d141561011d57505f5b6001546001828201116101325750505f610138565b01600190035b5f555f6001556074025ff35b5f5ffd`

Verified on [`evm.codes` playground](https://www.evm.codes/playground)
