### ISSUE TITLE
[Feature] Use AccessListResult type for createAccessList call

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1109]
### Component

network, json-rpc, provider, pubsub

### Describe the feature you would like

`createAccessList` returns an optional error if the transaction failed

https://github.com/paradigmxyz/reth/pull/9811

<img width="247" alt="image" src="https://github.com/user-attachments/assets/f20fe166-839f-4678-a76f-0b7b4de99271">

this is slightly annoying because this now returns an object that can represent a failed transaction

## TODO
* port reth type and update provider call
* add helper functions to AccessListresult that check if the result has an error and properly document

**Comment by mvares** [comment]
where can I add the `AccessListResult` type?

**Comment by mattsse** [comment]
here:

https://github.com/alloy-rs/alloy/blob/fa01c2ab9174abcd9521624ef341fcfea3d08356/crates/eips/src/eip2930.rs#L133-L142

**Comment by mvares** [comment]
Closes? @mattsse

**Comment by mvares** [comment]
closes? @mattsse
