### ISSUE TITLE
[Feature] add RPC eth_sendUserOperation for ERC-4337 Bunder

### ISSUE THREAD

**Issue by zeroknots** [alloy-rs/alloy#1111]
### Component

rpc

### Describe the feature you would like

We should add support for `eth_sendUserOperation` in alloy's RPC.

This could allow much easier communication with 4337 bundlers

### Additional context

https://eips.ethereum.org/EIPS/eip-4337#rpc-methods-eth-namespace

**Comment by jackpooleywc** [comment]
I would love to see this feature implemented.

**Comment by royvardhan** [comment]
Working on this.

**Comment by zeroknots** [comment]
> Working on this.

Do you have any code public that I could have a look at?

**Comment by royvardhan** [comment]
> > Working on this.
> 
> 
> 
> Do you have any code public that I could have a look at?

Nope. Currently blocked with https://github.com/paradigmxyz/reth/pull/10231

**Comment by royvardhan** [comment]
Will get this assigned to me once 👆🏻 is merged. Or anybody can take it right now.

**Comment by royvardhan** [comment]
@mattsse What do you think about this?
