### ISSUE TITLE
[Bug]  buffer overrun while deserializing

### ISSUE THREAD

**Issue by sxfreesky123** [alloy-rs/alloy#1115]
### Component

contract

### What version of Alloy are you on?

0.2.0

### Operating System

Windows

### Describe the bug

when i call decimals from contract (BEP20)
```
let contract = Usdt::new(contract_str.parse()?, provider);
let Usdt::decimalsReturn {_0:decimals} = contract.decimals().call().await?;
```
An error has occurred:  buffer overrun while deserializing

**Comment by DaniPopes** [comment]
Can you please provide the address and chain

**Comment by sxfreesky123** [comment]
> Can you please provide the address and chain

contract address: 0x638ff0E03eA3cbBDDE58708827Bf237e80A4d600
chainId: 97(0x61)

**Comment by DaniPopes** [comment]
I cannot reproduce:
```rust
use alloy::primitives::address;

alloy::sol! {
    #[sol(rpc)]
    interface IERC20 {
        function decimals() returns (uint256 decimals);
    }
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    let url = "https://data-seed-prebsc-1-s1.binance.org:8545/";
    let provider = alloy::providers::ProviderBuilder::new()
        .on_builtin(url)
        .await
        .unwrap();
    let c = IERC20::new(
        address!("638ff0E03eA3cbBDDE58708827Bf237e80A4d600"),
        &provider,
    );
    let IERC20::decimalsReturn { decimals } = c.decimals().call().await.unwrap();
    println!("decimals: {}", decimals);
}
```

Can you please enable tracing like I did here, run with `RUST_LOG=alloy=trace`, and see if maybe the RPC response is incorrect?

**Comment by sxfreesky123** [comment]
> I cannot reproduce:
> 
> ```rust
> use alloy::primitives::address;
> 
> alloy::sol! {
>     #[sol(rpc)]
>     interface IERC20 {
>         function decimals() returns (uint256 decimals);
>     }
> }
> 
> #[tokio::main]
> async fn main() {
>     tracing_subscriber::fmt::init();
> 
>     let url = "https://data-seed-prebsc-1-s1.binance.org:8545/";
>     let provider = alloy::providers::ProviderBuilder::new()
>         .on_builtin(url)
>         .await
>         .unwrap();
>     let c = IERC20::new(
>         address!("638ff0E03eA3cbBDDE58708827Bf237e80A4d600"),
>         &provider,
>     );
>     let IERC20::decimalsReturn { decimals } = c.decimals().call().await.unwrap();
>     println!("decimals: {}", decimals);
> }
> ```
> 
> Can you please enable tracing like I did here, run with `RUST_LOG=alloy=trace`, and see if maybe the RPC response is incorrect?

my error, it's not bug, thank you!
