### ISSUE TITLE
[Bug] deserialize rust primitives failed

### ISSUE THREAD

**Issue by programskillforverification** [alloy-rs/alloy#1121]
### Component

serde

### What version of Alloy are you on?

0.2.1

### Operating System

macOS (Apple Silicon)

### Describe the bug

The original code is

https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types-eth/src/transaction/request.rs#L825-L832

I rewrite the test
```rust
    #[test]
    fn serde_tx_request_additional_fields() {
        let s = r#"{"accessList":[],"data":"0x0902f1ac","to":"0xa478c2975ab1ea89e8196811f51a7b7ade33eb11","type":"0x02","sourceHash":"0xbf7e331f7f7c1dd2e05159666b3bf8bc7a8a3a9eb1d518969eab529dd9b88c1a"}"#;
        let req = serde_json::from_str::<WithOtherFields<TransactionRequest>>(s).unwrap();
        let result = req.other.get_deserialized::<f64>("sourceHash").unwrap().unwrap();
        println!("{:?}", result);
        assert!(false);
        // assert_eq!(
        //     req.other.get_deserialized::<B256>("sourceHash").unwrap().unwrap(),
        //     b256!("bf7e331f7f7c1dd2e05159666b3bf8bc7a8a3a9eb1d518969eab529dd9b88c1a")
        // );
    }
```
For `get_deserialized::<T>`, if T is `B256, U256 , String` or any alias type, it works properly. But for rust primitives, like `u128, int32, f64`, the result is error
```
invalid type: string \"0xbf7e331f7f7c1dd2e05159666b3bf8bc7a8a3a9eb1d518969eab529dd9b88c1a\", expected
```

**Comment by mattsse** [comment]
why are you trying to deserialize this into a f64, this type is b256, so this is failing as expected
