### ISSUE TITLE
[Bug] subscription id issue

### ISSUE THREAD

**Issue by HowHsu** [alloy-rs/alloy#1155]
### Component

provider, pubsub

### What version of Alloy are you on?

Latest

### Operating System

Linux

### Describe the bug

blockchains like Astar returns a 8 bytes String as subscription id, while Alloy only accept 32 byte hex string as subscription id, this causes issue:
                                                                                                             

Error: deserialization error: invalid value: string "7A05Kuieflh1Cozb", expected a 32 byte hex string at line 1 column 18
                                                             
Caused by:                                                                                                                
    invalid value: string "7A05Kuieflh1Cozb", expected a 32 byte hex string at line 1 column 18

I've printed the stack:
backtrace: Backtrace [{ fn: "alloy_pubsub::managers::in_flight::InFlight::fulfill" }, { fn: "alloy_pubsub::managers::req::Requ
estManager::handle_response" }, { fn: "alloy_pubsub::service::PubSubService<T>::handle_item" }, { fn: "alloy_pubsub::servi
ce::PubSubService<T>::spawn::{{closure}}" }, { fn: "tokio::runtime::task::core::Core<T,S>::poll" }, { fn: "tokio::runtime:
:task::raw::poll" }, { fn: "tokio::runtime::scheduler::multi_thread::worker::Context::run_task" }, { fn: "tokio::runtime::
scheduler::multi_thread::worker::Context::run" }, { fn: "tokio::runtime::context::scoped::Scoped<T>::set" }, { fn: "tokio:
:runtime::context::runtime::enter_runtime" }, { fn: "tokio::runtime::scheduler::multi_thread::worker::run" }, { fn: "tokio
::runtime::task::core::Core<T,S>::poll" }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll" }, { fn: "tokio::runt
ime::blocking::pool::Inner::run" }, { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace" }, { fn: "core::ops::
function::FnOnce::call_once{{vtable.shim}}" }, { fn: "std::sys::pal::unix::thread::Thread::new::thread_start" }]

**Comment by mattsse** [comment]
right, this should accept an arbitrary string as identifier

**Comment by HowHsu** [comment]
> right, this should accept an arbitrary string as identifier

Hi Mattsse, 

Any possibility to work around this for a short term, the blockchain rpc server I connected returns a 16 bytes string of letters and numbers as subscription id, e.g.  "7A05Kuieflh1Cozb". How can I hack the alloy code for short term use before the long term PR being merged?

Thanks in advance
Hao

**Comment by mattsse** [comment]
closed via #1163
