### ISSUE TITLE
[Feature] Support arbitrary subscription ids

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1158]
### Component

provider, pubsub

### Describe the feature you would like

this currently only supports u256 ids:

https://github.com/alloy-rs/alloy/blob/4a270df340d21359283b3d7fb2c1204baf9f4084/crates/pubsub/src/managers/in_flight.rs#L58-L70

and causes issues where servers don't return u256 as subscription ids #1155

## TODO

* introduce a new type that can handle both u256 and string:

```
pub enum SubscriptionId {
	/// Numeric id
	Num(U267),
	/// String id
	Str(String),
}
```

and use this as a replacement for the `server_id: U256` where used:

https://github.com/alloy-rs/alloy/blob/4a270df340d21359283b3d7fb2c1204baf9f4084/crates/pubsub/src/service.rs#L170-L170

**Comment by DaniPopes** [comment]
https://github.com/alloy-rs/alloy/blob/4a270df340d21359283b3d7fb2c1204baf9f4084/crates/json-rpc/src/common.rs#L26-L33

**Comment by HowHsu** [comment]
why do we use an Enum rather than directly use String as Id
