### ISSUE TITLE
[Feature] Extract some eip modules to separate repository

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1174]
### Component

meta-crate

### Describe the feature you would like

revm currently relies on
* eip2930
* eip7702

to make the upgrade path easier, it would be helpful to have these modules as separate crates 

## TODO
* move the modules to standalone crates `alloy-rs/eips`

**Comment by yash-atreya** [comment]
2930 and 7702 have been moved here https://github.com/alloy-rs/eips. Do we need to publish them to crates.io or we'll be using git revs?
