### ISSUE TITLE
[Bug] `contract` does not live long enough

### ISSUE THREAD

**Issue by rakanalh** [alloy-rs/alloy#1225]
### Component

contract

### What version of Alloy are you on?

alloy v0.3.0

### Operating System

Linux

### Describe the bug

I've updated the example `contract/interact_with_abi.rs` to call a contract inside a `clap::Subcommand`.

https://github.com/rakanalh/alloy-examples/blob/main/examples/contracts/examples/interact_with_abi.rs

Rust's borrow checker complains as follows:
```
error[E0597]: `contract` does not live long enough
  --> examples/contracts/examples/interact_with_abi.rs:44:4
   |
43 |             let contract = IWETH9::new(address.clone(), provider);
   |                 -------- binding `contract` declared here
44 |             contract.approve(address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"), U256::from(1)).await;
   |             ^^^^^^^^-----------------------------------------------------------------------------
   |             |
   |             borrowed value does not live long enough
   |             argument requires that `contract` is borrowed for `'static`
45 |         },
   |         - `contract` dropped here while still borrowed
```

Although it's unclear to me how the contract instance would not live as long as the call next line. Maybe i missing something here and hoping someone would shed some light over what's being borrowed here (&self?) and why it doesn't live as long as the next call.

**Comment by DaniPopes** [comment]
Limitation of the IntoFuture impl, using .call explicitly should fix it

**Comment by rakanalh** [comment]
Yea seems like the following works:
```
contract.approve(address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"), U256::from(1)).call().into_future().await;
```

**Comment by DaniPopes** [comment]
shouldnt need the into_future() there
