### ISSUE TITLE
[Bug] Can't sent private transactions

### ISSUE THREAD

**Issue by NicolasWent** [alloy-rs/alloy#1228]
### Component

consensus, eips, genesis

### What version of Alloy are you on?

0.3.0

### Operating System

None

### Describe the bug

When I am trying to send a private transaction using this:
https://alloy.rs/examples/transactions/send_private_transaction.html

The transaction is never included. I am looking at the explorer for the "from" address of the transaction is replaced by a random address not the one I signed.

I think it is because Flashbots may not support 2718 encoding. Is there any way to send using an older encoding?

**Comment by onbjerg** [comment]
It definitely supports 2718 encoding, as this is a prerequisite for EIP-1559, which flashbots supports. Please ensure the gas price is enough to get included, it might not be:)
