### ISSUE TITLE
[Bug] deploy contract with bytecode

### ISSUE THREAD

**Issue by sunliang711** [alloy-rs/alloy#1232]
### Component

rpc

### Operating System

Linux

### Describe the bug

Sending transaction without 'to' should be ok since empty 'to' means to deploy contract. But currently, alloy reports error: local usage error: missing properties: [("Wallet", ["to"])].The following is my code:
```
let tx = TransactionRequest::default().with_gas_price(price).with_input(vec![...]);
let receipt = provider.send_transaction(tx).await?.get_receipt().await?;
```

**Comment by onbjerg** [comment]
do `tx.into_create()`: https://docs.rs/alloy/latest/alloy/rpc/types/struct.TransactionRequest.html#method.set_create

**Comment by sunliang711** [comment]
> do `tx.into_create()`: https://docs.rs/alloy/latest/alloy/rpc/types/struct.TransactionRequest.html#method.set_create

Got it, thank you very much

**Comment by onbjerg** [comment]
Alternatively you can use `with_deploy_code` instead of `with_input`, which will also do `into_create` for you:) https://docs.rs/alloy/latest/alloy/network/trait.TransactionBuilder.html#method.with_deploy_code
