### ISSUE TITLE
[Feature] Invert alias and struct declaration for BlockNumHash

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1266]
### Component

consensus, eips, genesis

### Describe the feature you would like

same as #1264 but for `BlockNumHash` ref #1265

note: only swap the struct name and alias

**Comment by PanGan21** [comment]
Hi @mattsse  could it be that you mean `BlockHashOrNumber` in the ticket instead of `BlockNumHash`?

**Comment by mattsse** [comment]
closed by #1270
