### ISSUE TITLE
[Feature] Genesis Hardforks

### ISSUE THREAD

**Issue by refcell** [alloy-rs/alloy#1286]
### Component

consensus, eips, genesis

### Describe the feature you would like

`op-alloy` has a new `op-alloy-genesis` crate that introduces `Hardforks` into the genesis crate.

This issue is to upstream Hardforks into `alloy-genesis` as well.

### Additional context

https://github.com/alloy-rs/op-alloy/pull/97#discussion_r1758891100

**Comment by mattsse** [comment]
we want to solve this differently and maybe even extract the reth ethereum-forks crate from reth instead
