### ISSUE TITLE
[Feature] Add getters to `alloy_network_primitives::TransactionResponse`

### ISSUE THREAD

**Issue by emhane** [alloy-rs/alloy#1297]
### Component

rpc

### Describe the feature you would like

Add all getters for all fields of `alloy_rpc_types_eth::Transaction` as trait methods to `alloy_network_primitives::TransactionResponse`

**Comment by emhane** [comment]
also this one @garwahl?

**Comment by garwahl** [comment]
Yep can take this one too, thanks
