### ISSUE TITLE
[Feature] Add getters of `alloy_consensus::Header` to a new trait `BlockHeader`

### ISSUE THREAD

**Issue by emhane** [alloy-rs/alloy#1301]
### Component

consensus, eips, genesis

### Describe the feature you would like

Add new trait, called something like `BlockHeader`. Add a getter for all fields of `alloy_consensus::Header` as trait methods to this new trait. Set the new trait as trait bound for `alloy_network::Network`.

**Comment by klkvr** [comment]
@emhane we already have `HeaderResponse` trait which is set as bound to header response types on `Network`, couldn't we extend that https://github.com/alloy-rs/alloy/blob/347626b0609c31d6ea740d4a8c770e01b241004a/crates/network-primitives/src/traits.rs#L88 ?

**Comment by emhane** [comment]
`ConfigurEvmEnv` trait in reth deals with the consensus block type @klkvr

**Comment by emhane** [comment]
@garwahl would you like to do this one?

**Comment by garwahl** [comment]
@emhane Yep happy to take this! Feel free to assign me

**Comment by garwahl** [comment]
@emhane this looks completed by https://github.com/alloy-rs/alloy/pull/1302 already? Unless I'm mistaken

**Comment by emhane** [comment]
true, thanks @garwahl
