### ISSUE TITLE
[Bug] We need a major version bump due to #1292 being a breaking change

### ISSUE THREAD

**Issue by iajoiner** [alloy-rs/alloy#1307]
### Component

other

### What version of Alloy are you on?

0.3.6

### Operating System

Linux

### Describe the bug

https://github.com/alloy-rs/alloy/issues/1292 is a breaking change since it adds a [new enum variant](https://github.com/alloy-rs/alloy/blob/ff87573a204f4e5caa536a7d3a7ddfe39a83a957/crates/rpc-types-trace/src/geth/mod.rs#L123-L124) without `non-exhaustive` (see https://doc.rust-lang.org/cargo/reference/semver.html#enum-variant-new). This broke `revm-inspectors` and in turn `foundry` and `proof-of-sql` which I work on (see https://github.com/spaceandtimelabs/sxt-proof-of-sql/actions/runs/10927271217/job/30333055842?pr=166). It is probably a good idea to yank 0.3.6 and re-release it as 0.4.0 or more projects will be affected.

**Comment by mattsse** [comment]
sorry about this, we'll be more careful moving forward
