### ISSUE TITLE
[Feature] Add fallible spawn function for Anvil and Geth bindings

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#136]
### Component

nodes

### Describe the feature you would like

add `try_spawn` functions for 

https://github.com/alloy-rs/alloy/blob/61142b3fee367a9aee087d6cfac8e57abaaa2eb2/crates/node-bindings/src/anvil.rs#L216-L216

and 

https://github.com/alloy-rs/alloy/blob/61142b3fee367a9aee087d6cfac8e57abaaa2eb2/crates/node-bindings/src/geth.rs#L359-L359

**Comment by AnmolSirola** [comment]
@mattsse Can I work on this issue.

**Comment by EdsonAlcala** [comment]
@AnmolSirola are you working on this?
