### ISSUE TITLE
consensus: make `Header` `nonce` u64

### ISSUE THREAD

**Issue by tcoratger** [alloy-rs/alloy#1385]
### Component

consensus, eips, genesis

### Describe the feature you would like

At the moment, the nonce field in `Header` consensus struct is B64:

https://github.com/alloy-rs/alloy/blob/e01492a7ea88e13bcfddb357ade539fc5672baad/crates/consensus/src/header.rs#L77

To match the definition we expect in reth and other repos:

https://github.com/paradigmxyz/reth/blob/3a255a1cabd1f19399b42c1fe9bdcc130ac61c2e/crates/storage/codecs/src/alloy/header.rs#L30

it would be nice to make it u64, would you agree @mattsse ?

**Comment by mattsse** [comment]
technically this is 8bytes, I think we can keep B64, dont think this type is used that often and we can add a helper that converts this to u64

**Comment by SlayerPower** [comment]
hi love minecrafttt toooo, oye esta muy biennn

**Comment by varun-doshi** [comment]
Do we still need a helper to convert it to u64? If so I can take this

**Comment by mattsse** [comment]
I think we can leave this as b64, because for mainnet this field is now useless anyway and b64 would be more beneficial in case OP starts embedding encoded values in there
