### ISSUE TITLE
[Feature] Manually impl serialisation for `reth_rpc_types_eth::Transaction`

### ISSUE THREAD

**Issue by emhane** [alloy-rs/alloy#1409]
### Component

rpc

### Describe the feature you would like

Manually impl serde `Serialization` and `Deserialization`for `reth_rpc_types_eth::Transaction`. For the field `max_fee_per_gas`, this should use the json label `gasPrice` if the tx type is `< 2`, i.e. pre-eip1559. This way the field `gas_price` can be removed from the struct, as it is redundant

https://github.com/alloy-rs/alloy/blob/8d99c28da17232a26afe7af0251fde2cd00a89fe/crates/rpc-types-eth/src/transaction/mod.rs#L39-L154

**Comment by nadtech-hub** [comment]
I can make it up. Could you assign it to me?

**Comment by nadtech-hub** [comment]
I'm finalizing this one and want to make sure that serializer/deserializer is supposed to process only fields a certain type of transaction has, isn't it?

**Comment by nadtech-hub** [comment]
it's gonna get clear as long as I create PR I am just verifying the code

**Comment by nadtech-hub** [comment]
I guess this one and PR should be closed due to [1460](https://github.com/alloy-rs/alloy/pull/1460)

**Comment by nadtech-hub** [comment]
it only makes sense to cut input array if it contains function call data
