### ISSUE TITLE
[Bug] TxEnvelope rlp decoding returns unexpected length

### ISSUE THREAD

**Issue by triamazikamno** [alloy-rs/alloy#141]
### Component

consensus, eips, genesis

### What version of Alloy are you on?

https://github.com/alloy-rs/alloy#42778ba4

### Operating System

macOS (Apple Silicon)

### Describe the bug

```rust
    let raw_tx = hex::decode("02f86f0102843b9aca0085029e7822d68298f094d9e1459a7a482635700cbc20bbaf52d495ab9c9680841b55ba3ac080a0c199674fcb29f353693dd779c017823b954b3c69dffa3cd6b2a6ff7888798039a028ca912de909e7e6cdef9cdcaf24c54dd8c1032946dfa1d85c206b32a9064fe8").unwrap();
    let res = alloy_consensus::TxEnvelope::decode(&mut raw_tx.as_slice());
```
Returns `alloy_rlp::Error::UnexpectedLength`. Seems it's expecting a non-empty buffer here: https://github.com/alloy-rs/alloy/blob/42778ba44fbf9fdcfd44de81436f65d73e70ede2/crates/eips/src/eip2718.rs#L84
but it's empty at that point, as expected. Should this be checking for `buf.len() != 0` instead?

**Comment by triamazikamno** [comment]
Also, while on the same topic, legacy tx decoding is failing with `RlpError(UnexpectedString)` due to this part actually modifying the buffer: https://github.com/alloy-rs/alloy/blob/42778ba44fbf9fdcfd44de81436f65d73e70ede2/crates/eips/src/eip2718.rs#L67-L68
It works fine if changed to
```rust
let mut h_decode = *buf;
let h = Header::decode(&mut h_decode)?;
```
Not sure if it's copying the slice in this case though?

**Comment by mattsse** [comment]
where's the tx from?

**Comment by triamazikamno** [comment]
Just a random tx on ethereum: https://etherscan.io/tx/0xce4dc6d7a7549a98ee3b071b67e970879ff51b5b95d1c340bacd80fa1e1aab31.
Forge's cast is able to decode it (it's still using ethers for this part):
```
cast decode-transaction 02f86f0102843b9aca0085029e7822d68298f094d9e1459a7a482635700cbc20bbaf52d495ab9c9680841b55ba3ac080a0c199674fcb29f353693dd779c017823b954b3c69dffa3cd6b2a6ff7888798039a028ca912de909e7e6cdef9cdcaf24c54dd8c1032946dfa1d85c206b32a9064fe8
{
  "type": "0x02",
  "from": "0x001e2b7de757ba469a57bf6b23d982458a07efce",
  "to": "0xd9e1459a7a482635700cbc20bbaf52d495ab9c96",
  "gas": "0x98f0",
  "value": "0x0",
  "data": "0x1b55ba3a",
  "nonce": "0x2",
  "accessList": [],
  "maxPriorityFeePerGas": "0x3b9aca00",
  "maxFeePerGas": "0x29e7822d6",
  "r": "0xc199674fcb29f353693dd779c017823b954b3c69dffa3cd6b2a6ff7888798039",
  "s": "0x28ca912de909e7e6cdef9cdcaf24c54dd8c1032946dfa1d85c206b32a9064fe8",
  "v": 0
}
```

**Comment by Evalir** [comment]
@mattsse not a blocker for the alloy migration as we're not using the `TxEnvelope` but rather our own—but will take a look and fix as we probably want to use this down the line for other crates.

**Comment by prestwich** [comment]
the RLP stuff was hand-ported and needs a bunch of tests 😬
