### ISSUE TITLE
impl a better way to get the function from word

### ISSUE THREAD

**Issue by malik672** [alloy-rs/alloy#1413]
### Component

other

### Describe the feature you would like

for the function.rs in primitive crate, in the from_word function, we can simply create a function from a word using ` unsafe { Self(*(word.0.as_ptr() as *const [u8; 24])) }` than `   Self(FixedBytes(word[..24].try_into().unwrap()))`

**Comment by DaniPopes** [comment]
They're equivalent, but the current implementation doesn't use unsafe. I fail to see how it's better

https://godbolt.org/z/bx4v46nsj
