### ISSUE TITLE
[Feature] Adding EIP-712 Transaction support

### ISSUE THREAD

**Issue by dutterbutter** [alloy-rs/alloy#142]
### Component

consensus, eips, genesis

## Objective
Enhance Alloy to support EIP-712 transactions, enabling account abstraction / deployment for zkSync users that want to make use of alloy for their projects and tooling. In order to do so, alloy would need to support 712-transactions. Example:

```
pub struct Eip712Transaction {
    pub tx_type: U256,
    pub from: Address,
    pub to: Address,
    pub gas_limit: U256,
    pub gas_per_pubdata_byte_limit: U256,
    pub max_fee_per_gas: U256,
    pub max_priority_fee_per_gas: U256,
    pub paymaster: Address,
    pub nonce: U256,
    pub value: U256,
    pub data: Bytes,
    pub factory_deps: Vec<Bytes>,
    pub paymaster_input: Bytes,
    pub chain_id: U256,
}
```

### Resources

There is an initial implementation in zkSync `rust-web3-rs sdk` of 712-transactions which can be viewed here: [**712-tx**](https://github.com/lambdaclass/zksync-web3-rs/tree/main/src/eip712). It would be great to be able to extend alloy to include this functionality / support. 

- `rust-web3-rs sdk`: https://github.com/lambdaclass/zksync-web3-rs/
- Relevant docs: https://docs.zksync.io/zk-stack/concepts/transaction-lifecycle.html#eip-712-0x71

**Comment by prestwich** [comment]
This sort of functionality should be added as `ProviderExt` traits in separate crates, similar to #84

**Comment by nbaztec** [comment]
@prestwich is there an existing implementation that we can use as an example?
