### ISSUE TITLE
[Feature] Add rpc types for wallet_ namespace

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1420]
### Component

rpc

### Describe the feature you would like

just like txpool,eth,trace these types should go into another rpc-types-wallet crate and should include rpc type bindings for various `wallet_` endpoints

https://github.com/ethereum/ERCs/blob/01f41b608ae7e6cf7ef6369144b62b954dd63a1e/ERCS/erc-7715.md#wallet-managed-sessions

https://eips.ethereum.org/EIPS/eip-5792#wallet_sendcalls

**Comment by nadtech-hub** [comment]
Do you mind if I do this?

**Comment by mattsse** [comment]
please go for it

**Comment by mattsse** [comment]
there's some wip here

https://github.com/paradigmxyz/alphanet/pull/129/files#diff-f4101dafa4b2873ece04cc3c059d373ddd9143026a68c62c8e9431e7d3eb5b3aR35 which you can take

**Comment by nadtech-hub** [comment]
Did you mean to add wallet_sendCalls related types? I implemented all types in both EIPs.
