### ISSUE TITLE
[Feature] forkchoice casing is inconsistent in alloy-rpc-types-engine

### ISSUE THREAD

**Issue by Eduardogbg** [alloy-rs/alloy#1421]
### Component

rpc

### Describe the feature you would like

It's not a feature, just a question I have about something in the codebase that I found weird: in the forkchoice module at alloy-rpc-types-engine, for some types and variables the casing for forkchoice is ForkChoice or FORK_CHOICE instead of the usual forkchoice Forkchoice FORKCHOICE. It's not a big deal but I was wondering if there was a reason for that. If there is none and also you don't want to change please feel free to close this issue.

**Comment by mattsse** [comment]
> the usual forkchoice Forkchoice

where is the usual defined?

can you please link the relevant code, can't really comment on this otherwise

**Comment by Eduardogbg** [comment]
ok I did some digging and apparently some projects do use FORK_CHOICE, and I'm not arguing on the merits of each choice (though the Engine API spec uses forkchoice, I'm not sure about other specs that may conflict with it), I was just wondering if there was a reason for this inconsistency. But seeing that it only happens on internal variables and those names don't get serialized it's not an issue at all. Sorry for wasting your time on this
