### ISSUE TITLE
[Feature] Parse "secretKey": "0x" as None

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1445]
### Component

serde

### Describe the feature you would like

ref https://github.com/paradigmxyz/reth/issues/11611

for this we need a custom serde deserialize fn

https://github.com/alloy-rs/alloy/blob/aee55796556d5309136a532da1093f85d4c2d9b8/crates/genesis/src/lib.rs#L219-L220

that deserializes to string first and returns none if the content is "0x"

**Comment by 0xriazaka** [comment]
Can i take this?
