### ISSUE TITLE
[Feature] feat(`rpc-types`/`eips`): Unify or provide `From` impls for duplicated types, such as `AccessList`

### ISSUE THREAD

**Issue by Evalir** [alloy-rs/alloy#147]
### Component

consensus, eips, genesis, rpc

### Describe the feature you would like

Right now, there's a few types between `rpc-types` and `eips` which could be consolidated, such as the `AccessList` type, although the types in `eips` do implement different utilities like arbitrary traits, while the types in `rpc-types` are only concerned with rpc.

If we don't want to unify them, we can provide `From` impls between them to avoid having to write conversion functions whenever we use both.

**Comment by mattsse** [comment]
I think we want to unify them, Accesslist format is always the same

moving this to the lowest common trait in the tree makes the most sense to me (eips)?

**Comment by prestwich** [comment]
Closing as i believe that access list has been pushed down
