### ISSUE TITLE
[Feature] Treat empty address filters as non matching if both are not empty

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1470]
### Component

rpc

### Describe the feature you would like

ref https://github.com/paradigmxyz/reth/issues/11711

this will always be true if empty:

https://github.com/alloy-rs/alloy/blob/440ddcb872a47105ec18e470c8750258d863a610/crates/rpc-types-trace/src/filter.rs#L170-L170

which wasn't the case pre https://github.com/alloy-rs/alloy/commit/338b5b94daddbf8a5bedff3dfc5f4f5c4fcdf177

and is also not how https://github.com/erigontech/erigon/blob/72ab70be8b28964a8446e52b7a9975958c6726bf/turbo/jsonrpc/trace_filtering.go#L238-L289 behaves

**Comment by jsvisa** [comment]
let me fix this one.
