### ISSUE TITLE
[Bug] Sol macro failed to create contract instance

### ISSUE THREAD

**Issue by 1000teslas** [alloy-rs/alloy#1482]
### Component

contract

### What version of Alloy are you on?

0.4.2

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I use Sol! macro failed to create the contract instance when there's custom struct, the `contract::new` is not found.

Example:

```

use alloy::{
    providers::{Provider, ProviderBuilder},
    primitives::address,
    sol,
};
use eyre::Result;

sol! {
    struct cooldownRequest {
        bool exists;
    }
    contract TestContract {
        mapping(address => cooldownRequest) public balance;
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let provider = ProviderBuilder::new().with_recommended_fillers().on_anvil_with_wallet();
    let contract = TestContract::new(address!("ab5801a7d398351b8be11c439e05c5b32"), provider);
    Ok(())
}
```

which gives:

```
cannot find function `new` in module `TestContract`
not found in `TestContract`
```

However, if there's no custom struct, we can create the new contract instance smoothly.

The similar problem happens if I use:
1. raw solidity code as above 2. abi 3. points to the .sol file.

**Comment by yash-atreya** [comment]
You need to add the `#[sol(rpc)]` above `TestContract` like so:

```rust
sol! {
    struct cooldownRequest {
        bool exists;
    }
    #[sol(rpc)]
    contract TestContract {
        mapping(address => cooldownRequest) public balance;
    }
}
```
