### ISSUE TITLE
[Feature] Add `Transaction::to_input` function

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1492]
### Component

consensus, eips, genesis

### Describe the feature you would like

currently input returns a slice even though we know the tx types internally always use `Bytes`, which makes it expensive to obtain a `Bytes` instance.

we should add

```rust
fn to_input(&self) -> Bytes
```

for this, this way cloning the input is cheap

cc @tcoratger

**Comment by DaniPopes** [comment]
https://github.com/alloy-rs/alloy/pull/1487 ?

**Comment by mattsse** [comment]
makes sence although this wouldn't work for transactions (non-existing ones) that don't have input. but I guess we can make that assumption
