### ISSUE TITLE
[Question]  how can we decode transaction data ?

### ISSUE THREAD

**Issue by Aviksaikat** [alloy-rs/alloy#1534]
### Component

other

### Describe the feature you would like

As we all know, we can decode transaction data when a known method is called like this.

```rs
[...]
fn main() {
    let input = "0x38ed173900000000000000000000000000000000000000000001a717cc0a3e4f84c00000000000000000000000000000000000000000000000000000000000000283568400000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000201f129111c60401630932d9f9811bd5b5fff34e000000000000000000000000000000000000000000000000000000006227723d000000000000000000000000000000000000000000000000000000000000000200000000000000000000000095ad61b0a150d79219dcf64e1e6cc01f0b64c4ce000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7";
    let input = hex::decode(input)?;

    // Decode the input using the generated `swapExactTokensForTokens` bindings.
    let decoded = swapExactTokensForTokensCall::abi_decode(&input, false);

[...]
}
```

But how can we decode the data when we don't know which method is called? We can read the function signature data from the first 4 bytes of data, which can be used to determine what function is called. But how can we use `alloy-rs` to decode the data further using abi?

**Comment by mattsse** [comment]
there's https://docs.rs/alloy-core/latest/alloy_core/sol_types/trait.SolCall.html#method.abi_decode_raw for decoding without the selector

**Comment by yash-atreya** [comment]
Resolved by comment above.
