### ISSUE TITLE
Maybe improve tower::Service trait types?

### ISSUE THREAD

**Issue by 63b8e7lmk1jv9c0ovus4hqkcasqgp0ed** [alloy-rs/alloy#156]
### Component

network, json-rpc, rpc, transports

### Describe the feature you would like

If I understood everything correctly, the current types are

```rust
pub enum ResponsePacket<Payload = Box<RawValue>, ErrData = Box<RawValue>> {
    Single(Response<Payload, ErrData>),
    Batch(Vec<Response<Payload, ErrData>>),
}
```

The overall tower::Service Error type is
```rust
type Error = alloy_transport::TransportError;
```

In a single call type, if there's a transport error or serialization error, it can return an error for tower::Service. Though, for a single failure in a batch call, the responses can only return RPC errors. If a single RPC call in the batch needs to return a serialization or transport related error, it must fail all of the other calls in the batch.

I tried to fix this issue in the transport I was writing by using transport and serialization errors as RPC errors, which isn't consistent with how provider errors are supposed to be interpreted.

**Comment by prestwich** [comment]
> If a single RPC call in the batch needs to return a serialization or transport related error, it must fail all of the other calls in the batch.

In what situations do you expect this to occur? 

If there is a deserialization issue with a single response in a batch, it means that the serialization of the entire batch is potentially invalid

All responses in a batch are transported as a unit, so a transport error, for any response in the batch is a transport error for all responses in a batch.

**Comment by 63b8e7lmk1jv9c0ovus4hqkcasqgp0ed** [comment]
I converted to a string, parsed the string from Javascript, used a third party API, did a JSON.stringify, and finally a serde_from_str. It just seemed possible to fail sometimes with differences between how something might be parsed or turned into a string. 

> All responses in a batch are transported as a unit, so a transport error, for any response in the batch is a transport error for all responses in a batch.

I was thinking in the context of that the third party API might not allow batch requests. (The transport just makes it seem possible) 

--- 

In comparison to ethers, I'm not really sure there were many people that tried to write providers or transports, so I don't know if really matters that much. I just wanted to personally keep track of any potential errors for what I was writing.

**Comment by prestwich** [comment]
> I converted to a string, parsed the string from Javascript, used a third party API, did a JSON.stringify, and finally a serde_from_str. It just seemed possible to fail sometimes with differences between how something might be parsed or turned into a string

Im not sure what you're doing here or why but it sounds like an unsupported use

**Comment by 63b8e7lmk1jv9c0ovus4hqkcasqgp0ed** [comment]
It's not a huge concern, I just thought it might be an improvement. It's not difficult to imagine other scenarios where a batch request could be thousands or millions of requests that are transferred to somewhere with really low latency for individual requests. I guess those could be resent to the RPC too though, so maybe not the best example.

I don't think this really matters.
