### ISSUE TITLE
[Bug] Non-semver breaking change in 0.5.4

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#1562]
### Component

meta-crate

### What version of Alloy are you on?

0.5.4

### Operating System

None

### Describe the bug

alloy@0.5.4 introduced non-semver breaking changes via #1550. the re-exported 7702 package changed the return value of signature via [#13](https://github.com/alloy-rs/eips/pull/13)

to reproduce: 
`cd reth && git checkout 8b1dfcc && cargo update && cargo c`

**Comment by nadtech-hub** [comment]
I can take on this one
