### ISSUE TITLE
[Feature] Check if a bundle is confirm or not

### ISSUE THREAD

**Issue by chen4903** [alloy-rs/alloy#1580]
### Component

transports

### Describe the feature you would like

I use flashbot to send a bundle to blockchain and get a bundle hash, but I don't know if this bundle confirm or not. It would be great if Alloy could provide a functionality to check the transaction.

Here is a repo that could be referred: https://github.com/onbjerg/ethers-flashbots/blob/master/src/pending_bundle.rs

**Comment by zerosnacks** [comment]
Hi @chen4903 thanks for your suggestion, the correct place to implement this would indeed be https://github.com/leruaa/alloy-mev/issues/11 

Assuming this doesn't require implementation changes on Alloy's side, marking as duplicate.

cc @leruaa
