### ISSUE TITLE
[Feature] Add support for EIP4844 transactions to consensus crate 

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#162]
### Component

consensus, eips, genesis

### Describe the feature you would like

Add both EIP4844 variants to

https://github.com/alloy-rs/alloy/tree/main/crates/consensus/src/transaction

https://github.com/paradigmxyz/reth/blob/add3c6a3a2ae0cecd8627533bbc5688a456435ad/crates/primitives/src/transaction/eip4844.rs

https://github.com/paradigmxyz/reth/blob/add3c6a3a2ae0cecd8627533bbc5688a456435ad/crates/primitives/src/transaction/sidecar.rs#L48-L58

with and without sidecar

**Comment by Evalir** [comment]
Closed with #185
