### ISSUE TITLE
`Network::HeaderResponse` does not contain hash

### ISSUE THREAD

**Issue by Wollac** [alloy-rs/alloy#1626]
### Component

network, json-rpc

### What version of Alloy are you on?

alloy-network v0.6.0

### Operating System

None

### Describe the bug

With the recent changes in #1573, there is no longer a way to get the block hash from a generic `alloy_network::Network` response. The `HeaderResponse` now only contains the actual header, but no additional fields like the hash.
I expected that there would be a wrapper (similar to `alloy_rpc_types_eth::Header`) that would either store this hash directly, or if for some reason this is considered too Ethereum specific, at least some `other_fields` mechanism. Such behavior would also be consistent with the `BlockResponse`, and previous versions of alloy allowed direct access to the hash.

**Comment by mattsse** [comment]
right, thanks for flagging.

imo @klkvr the easiest way to make this convenient is introducing a trait (`HeaderResponse`) or we can add some restriction to `Sealed<&Self::Header>`.

the former is likely easier
