### ISSUE TITLE
Replace `thiserror-no-std` with `thiserror` v2

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/alloy#1628]
### Component

other

### Describe the feature you would like

`thiserror` released version 2 which includes no_std support: https://github.com/dtolnay/thiserror/releases/tag/2.0.0

`thiserror` must also be added with `default-features = false`

This requires MSRV 1.81: https://github.com/alloy-rs/alloy/pull/1552

**Comment by nadtech-hub** [comment]
🙋‍♂️

**Comment by zerosnacks** [comment]
yay! unblocked by https://blog.rust-lang.org/2024/11/28/Rust-1.83.0.html
