### ISSUE TITLE
Remove async from PubSubFrontend::unsubscribe

### ISSUE THREAD

**Issue by ZanCorDX** [alloy-rs/alloy#163]
### Component

providers, pubsub

### Describe the feature you would like

Remove async from PubSubFrontend::unsubscribe since it's not really async.
It's stopping me from being able to implement a RAII object that unsubscribes on drop.

**Comment by prestwich** [comment]
would you consider submitting your RAII types for inclusion in the main repo?

**Comment by ZanCorDX** [comment]
It's a very preliminary stuff while you finish streams stuff:
