### ISSUE TITLE
[Bug]  Deserialization Error for Celo (Alfajores) or Blast (Sepolia) Test Networks

### ISSUE THREAD

**Issue by necmettindev** [alloy-rs/alloy#1635]
### Component

consensus, eips, genesis, rpc, serde

### What version of Alloy are you on?

0.6.2

### Operating System

Linux

### Describe the bug

I encountered an error while working with Alloy.rs related for the Celo or Blast test networks. The error appears to be a deserialization issue when processing block transactions.

Error message:

` Error: RPCTransportError(DeserError { err: Error("data did not match any variant of untagged enum BlockTransactions", line: 1, column: 6117), text: "{\"baseFeePerGas\":\"0x5d21dba00\",\"blobGasUsed\":\"0x0\",\"difficulty\":\"0x0\",\"excessBlobGas\":\"0x0\",\"extraData\":\"0x\",\"gasLimit\":\"0x1c9c380\",\"gasUsed\":\"0x11edc5\",\"hash\":\"0xfe101318bfde3892a876fc13ae29a16626485a59fb4c4541469a41067e068cf0\",\"logsBloom\":\"0x00800000000000000000040000000000000008400002000000000000000000000000000000000000000000000000000800000000000000040800000000000002000000000000000000000000000100000000000004000000000000000000000002100000000000000000000000008000000020000000000040000000000020000000000000000040400000000000000000000000000000000000000001000000000010800000004000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000100010000000000000001000000000000800000010000000000000000000020000000000000000000\",\"miner\":\"0x4200000000000000000000000000000000000011\",\"mixHash\":\"0x7f6387918b4d1d1892ef7ac06a61b172ee0ac706d65433f1ce8e4ed4bf5f8d49\",\"nonce\":\"0x0000000000000000\",\"number\":\"0x1cbd3cd\",\"parentBeaconBlockRoot\":\"0x354256bf53c3efb874cd0d1b17a49233ed38d5125f7df94577d9948612db49cf\",\"parentHash\":\"0xffb3e5d03da2b63b4d3a30e5a22a6f07a2837471a8ecd3c797c117da9efe3d00\",\"receiptsRoot\":\"0xaa217aaf84948b6f40ec0d8e288b6ac6cdaae136187b2fcbd171af366b81551a\",\"sha3Uncles\":\"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\",\"size\":\"0x739\",\"stateRoot\":\"0x3155d8aeb241643fbda9b8b0d144fe121e29a8fa109a847c4a250a2d819107f7\",\"timestamp\":\"0x672e5885\",\"totalDifficulty\":\"0x0\",\"transactions\":[{\"blockHash\":\"0xfe101318bfde3892a876fc13ae29a16626485a59fb4c4541469a41067e068cf0\",\"blockNumber\":\"0x1cbd3cd\",\"from\":\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"gas\":\"0xf4240\",\"gasPrice\":\"0x0\",\"hash\":\"0x7c6cec8a5fb266a1fda9932fbd159cf4a1c752319acdc6dbe5766dcc78005e6d\",\"input\":\"0x440a5e2000000558000c5fc5000000000000000300000000672e584800000000002931e6000000000000000000000000000000000000000000000000000000000000000b00000000000000000000000000000000000000000000000000000000000000012b3e33860ee24ba91b1b26ed8ea24770e787a824b2578d7291a60c7e69b3f8660000000000000000000000006f9cc6bfe1a0b446a36453d150905bbd6a4784e0\",\"nonce\":\"0x393d4d\",\"to\":\"0x4200000000000000000000000000000000000015\",\"transactionIndex\":\"0x0\",\"value\":\"0x0\",\"type\":\"0x7e\",\"v\":\"0x0\",\"r\":\"0x0\",\"s\":\"0x0\",\"sourceHash\":\"0xabe8178dd4daaf8fc87f56043735e2fcba2b14fb30df52f88937faedd545a139\",\"mint\":\"0x0\",\"depositReceiptVersion\":\"0x1\"},{\"blockHash\":\"0xfe101318bfde3892a876fc13ae29a16626485a59fb4c4541469a41067e068cf0\",\"blockNumber\":\"0x1cbd3cd\",\"from\":\"0x840b32f30e1a3b2e8b9e6c0972eba0148e22b847\",\"gas\":\"0x6c83d\",\"gasPrice\":\"0x66720b300\",\"maxFeePerGas\":\"0xc393e6d00\",\"maxPriorityFeePerGas\":\"0x9502f900\",\"hash\":\"0xbe75323a576e2cf59430346b89d08573b40c984ac32afe643384f60033bc250c\",\"input\":\"0x80e50744000000000000000000000000874069fa1eb16d44d622f2e0ca25eea172369bc1000000000000000000000000000000000000000000008665ad852ceed8b185b00000000000000000000000003e4dbf92e5f19be41e1faa6368779418a610191f0000000000000000000000000000000000000000000000000000000000000000\",\"nonce\":\"0x7f940\",\"to\":\"0xfdd8bd58115ffbf04e47411c1d228ecc45e93075\",\"transactionIndex\":\"0x1\",\"value\":\"0x0\",\"type\":\"0x2\",\"accessList\":[],\"chainId\":\"0xaef3\",\"v\":\"0x0\",\"r\":\"0x8203e26da3a0d1ef0377297ae952ef63bec37486b5591db7ac2411c6e346ebc7\",\"s\":\"0x7bc3fff58d5119072ace5699e3d24918c46b2cebb3185e65ab638a8b948ff17e\",\"yParity\":\"0x0\"},{\"blockHash\":\"0xfe101318bfde3892a876fc13ae29a16626485a59fb4c4541469a41067e068cf0\",\"blockNumber\":\"0x1cbd3cd\",\"from\":\"0x98cf3d869cac0c9fe88212e89db467d571d794c8\",\"gas\":\"0x6d5f1\",\"gasPrice\":\"0x66720b300\",\"maxFeePerGas\":\"0xc393e6d00\",\"maxPriorityFeePerGas\":\"0x9502f900\",\"hash\":\"0x91dd26faf689b09c26c28e9f736f5ad502ba4e56e797b5b16b3ba5200113eb82\",\"input\":\"0x80e50744000000000000000000000000bacee37d31b9f022ef5d232b9fd53f05a531c1690000000000000000000000000000000000000000000001a2b3e785d2008240000000000000000000000000005af201ae60653fe4239404cf3bbf62eac7868f010000000000000000000000000000000000000000000000000000000000000000\",\"nonce\":\"0x892f\",\"to\":\"0xfdd8bd58115ffbf04e47411c1d228ecc45e93075\",\"transactionIndex\":\"0x2\",\"value\":\"0x0\",\"type\":\"0x2\",\"accessList\":[],\"chainId\":\"0xaef3\",\"v\":\"0x0\",\"r\":\"0x53b31b59a38ffd28adb200828d416e9958cafaf55a257276d1495e4e941b761f\",\"s\":\"0x409cb113874a1fe33971c5604b1f180848db0956a2cef3b80b2e5e2128d56f06\",\"yParity\":\"0x0\"},{\"blockHash\":\"0xfe101318bfde3892a876fc13ae29a16626485a59fb4c4541469a41067e068cf0\",\"blockNumber\":\"0x1cbd3cd\",\"from\":\"0xad41311e7f56d72a73801834ea931f1c5a56ed45\",\"gas\":\"0x5cc81\",\"gasPrice\":\"0x66720b300\",\"maxFeePerGas\":\"0xc393e6d00\",\"maxPriorityFeePerGas\":\"0x9502f900\",\"hash\":\"0x312173a97bbc66de25e5bed6c7cda07e17d77dbdfa5a52b122fcdfaa88212cc8\",\"input\":\"0x80e5074400000000000000000000000040dc8528167557353fdcd98548ab2139a670dd0b0000000000000000000000000000000000000000021d61acbe15c78cdc43f7b00000000000000000000000005b185a2b01022a4303655d1242f8484804628e35000000000000000000000000c331b4761b9ea4671060064086faf340591cf24e\",\"nonce\":\"0x186cf\",\"to\":\"0xfdd8bd58115ffbf04e47411c1d228ecc45e93075\",\"transactionIndex\":\"0x3\",\"value\":\"0x0\",\"type\":\"0x2\",\"accessList\":[],\"chainId\":\"0xaef3\",\"v\":\"0x0\",\"r\":\"0x8175eca35105e62b577357464dda77d49d8f98e404cc728ff10ad4a2e3ad9a63\",\"s\":\"0x17b77961221763b6115af33753555523b9e45227543bb9532c7f2b117594673c\",\"yParity\":\"0x0\"},{\"blockHash\":\"0xfe101318bfde3892a876fc13ae29a16626485a59fb4c4541469a41067e068cf0\",\"blockNumber\":\"0x1cbd3cd\",\"from\":\"0x5d2d590bddf1e7c2f82f9063b01fdbac7ff1570c\",\"gas\":\"0x5e29c\",\"gasPrice\":\"0x66720b300\",\"maxFeePerGas\":\"0xc393e6d00\",\"maxPriorityFeePerGas\":\"0x9502f900\",\"hash\":\"0xe12612b82384671356c89fe08d4e13927edffbf7b44182efc1eb5695ce1dccb3\",\"input\":\"0x80e50744000000000000000000000000a1a8003936862e7a15092a91898d69fa8bce290c00000000000000000000000000000000000000000000d3bdb550d492a4e970700000000000000000000000002ad22a0ed4f8798280c8a48e13144758bfeac3770000000000000000000000002608bed69addf52c464d3c66429262c26b7f07ce\",\"nonce\":\"0x2fe0e\",\"to\":\"0xfdd8bd58115ffbf04e47411c1d228ecc45e93075\",\"transactionIndex\":\"0x4\",\"value\":\"0x0\",\"type\":\"0x2\",\"accessList\":[],\"chainId\":\"0xaef3\",\"v\":\"0x0\",\"r\":\"0xd1cb59011b1b7e71a787151ed1d203934be915a61fa9cc66d55b10cda853cddc\",\"s\":\"0x2c7229cdac9ad4a39e31bff29392f0d4cd2c680e390915e92f82055bd5709cc6\",\"yParity\":\"0x0\"}],\"transactionsRoot\":\"0xb3dc0ec856155f4d81642288306b8d37a5696ab5a092be8da18d126d70ce16c7\",\"uncles\":[],\"withdrawals\":[],\"withdrawalsRoot\":\"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\"}" })`

**Comment by necmettindev** [comment]
I have verified that there are no issues when using Ethereum Sepolia and Polygon Amoy networks. The problem seems to be isolated to the Celo and Blast test networks.

**Comment by klkvr** [comment]
After latest update default `Ethereum` network is not suitable for networks with non-ethereum transaction types like OP networks with 0x7e deposit transaction

Consider using `AnyNetwork` for arbitrary networks: 
https://alloy.rs/examples/advanced/any_network.html
https://github.com/alloy-rs/alloy/blob/b08798cba2ebf3d78c8e6e0dcc725be413a337b5/crates/network/src/any/mod.rs#L53

Or `Optimism` network for OP-stack networks:
https://github.com/alloy-rs/op-alloy/blob/c24df6b58323eaa55e45be7fc810ac8ffd2fa875/crates/network/src/lib.rs#L19
