### ISSUE TITLE
[Bug] TxEnvelop json decoding fails with confusing error message

### ISSUE THREAD

**Issue by ufoscout** [alloy-rs/alloy#1689]
### Component

serde

### What version of Alloy are you on?

alloy v0.6.4

### Operating System

Linux

### Describe the bug

Deserializing a TxEnvelop produces a confusing error message: `Error("data did not match any variant of untagged enum MaybeTaggedTxEnvelope", line: 0, column: 0)` independently of the real error.

For example, this fails and there's no way to know why:
```rust
#[test]
fn test_serde_tx_envelop() {
    let data = r#"
    {
        "hash":"0x0000000000000000000000000000000000000000000000000000000000000000",
        "input":"0x",
        "r": "0x1",
        "s": "0x0",
        "v": "0x1",
        "gas":"0x2710",
        "from":"0x0202020202020202020202020202020202020202",
        "to":null,
        "value":"0x0",
        "nonce":"0x0",
        "gasPrice":"0x4e20",
        "type":"0x0"
    }
    "#;
    let _tx: TxEnvelope = serde_json::from_str(data).unwrap();
}
```

I am not sure why, but the error disappears if you change from `"v": "0x1"` to `"v": "0x1c"`.

This test also fails because the hash length is 63 instead of 64, but the error reported makes it impossible to find it:
```rust
#[test]
fn test_serde_tx_envelop() {
    let data = r#"
    {
        "hash":"0x00000000000000000000000000000000000000000000000000000000000000",
        "input":"0x",
        "r": "0x1",
        "s": "0x0",
        "v": "0x1c",
        "gas":"0x2710",
        "from":"0x0202020202020202020202020202020202020202",
        "to":null,
        "value":"0x0",
        "nonce":"0x0",
        "gasPrice":"0x4e20"
    }
    "#;
    let _tx: TxEnvelope = serde_json::from_str(data).unwrap();
}
```

**Comment by klkvr** [comment]
Did you get this JSON payload from a real RPC response?

**Comment by Toeplitz** [comment]
I'm getting the same error on my base network provider with this code:
```
    let block = provider.get_block_by_number(block_num, BlockTransactionsKind::Hashes).await?;

    if let Some(block) = block {
        // let txs = block.transactions.as_transactions().unwrap_or_default();
        let txs = block.transactions.as_hashes().unwrap();

        for hash in txs {
            let tx = provider.get_transaction_by_hash(*hash).await?;
            println!("tx = {:#?}", tx)
        }
```

Gives error:

> 
> Error: deserialization error: data did not match any variant of untagged enum MaybeTaggedTxEnvelope at line 1 column 888
> 
> Caused by:
>     data did not match any variant of untagged enum MaybeTaggedTxEnvelope at line 1 column 888

Relate to the bug I reported here: https://github.com/alloy-rs/alloy/issues/1716

The code works fine on the ethereum network.

**Comment by mattsse** [comment]
closing this per https://github.com/alloy-rs/alloy/pull/1810
