### ISSUE TITLE
[Feature] Alloy to easily convert from alloy_rpc_types::Transaction to alloy_concensus::transaction::Transaction

### ISSUE THREAD

**Issue by ZanCorDX** [alloy-rs/alloy#169]
### Component

network, json-rpc

### Describe the feature you would like

The reason I need this right now is to be able to subscribe to newPendingTransactions and generate a rlp encoded txs from the tx stream.

**Comment by DaniPopes** [comment]
This is not done yet, right? cc @mattsse @onbjerg
RLP <-> RPC

**Comment by onbjerg** [comment]
it is not

**Comment by prestwich** [comment]
ideally this should be done by embedding a consensus transactionenvelope into the rpc response

**Comment by mattsse** [comment]
cc @klkvr 

imo we could either solve this by impl a tryform to consensus transaction from rpc
or solve this via some helper trait

**Comment by prestwich** [comment]
reopening due to ongoing work

**Comment by prestwich** [comment]
closed by #344 and #338 and #365
