### ISSUE TITLE
[Bug] Cannot fetch blocks with BlockTransactionsKind::Full on base network

### ISSUE THREAD

**Issue by Toeplitz** [alloy-rs/alloy#1716]
### Component

provider, pubsub

### What version of Alloy are you on?

0.7.0

### Operating System

Linux

### Describe the bug

On Base I try to fetch transaction data with this code:
`
let block = provider.get_block_by_number(block_num, BlockTransactionsKind::Full).await?;
`
But I get an error:

> 
> Error: deserialization error: data did not match any variant of untagged enum BlockTransactions at line 1 column 242358
> Caused by:
>     data did not match any variant of untagged enum BlockTransactions at line 1 column 242358

Using BlockTransactionsKind::Hashes works fine, but then 
`
let tx = provider.get_transaction_by_hash(*hash).await?;
`
Will cause a similar error.

The same code works fine on the ethereum network. Note that I'm running the base node in snap sync mode, if that can cause problems (I'm not sure):
https://github.com/base-org/node/blob/923f3407cba5b35b0cefca93ef5060e10ba89850/.env.mainnet#L44

**Comment by mattsse** [comment]
closing as dup of #1689 

if you use the `Ethereum` network then this will fail because it doesn't support OP's deposit txs, there's op-alloy `OpNetwork` or the `AnyNetwork`

**Comment by Toeplitz** [comment]
@mattsse thanks for the reply. Can you please be more specific, I don't understand what I have to change.

**Comment by mattsse** [comment]
ptal 

https://github.com/alloy-rs/examples/blob/3b6d4a7cb465a0cb62a396735a8e26baa188ea55/examples/advanced/examples/any_network.rs#L54

alternatively you can use the op specific network that is provided via the alloy-op-network crate:

https://github.com/alloy-rs/op-alloy/tree/main/crates/network
