### ISSUE TITLE
Make blob gas price calculation functions const

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/alloy#1725]
https://github.com/alloy-rs/alloy/blob/0bcfdf641357695a25eb335a0754fb6cca573af4/crates/eips/src/eip4844/mod.rs#L136

by making the assert_ne into an assert these functions can be made const

**Comment by nadtech-hub** [comment]
:hand:

**Comment by klkvr** [comment]
@nadtech-hub assigned
