### ISSUE TITLE
[Feature] Make `Transaction: Typed2718`

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1735]
### Component

consensus, eips, genesis

### Describe the feature you would like

the transaction trait currently has its own `fn ty` function.

we can unify this with the newer `Typed2718` trait by 

1. remove `fn ty` from `trait Transaction`
2. require `trait Transaction: Typed2718`

**Comment by nadtech-hub** [comment]
:raised_back_of_hand:
