### ISSUE TITLE
[Feature] Add specialized geth tracer

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#1738]
### Component

network, json-rpc

### Describe the feature you would like

deserializing the gethtrace can be ambiguous:

https://github.com/alloy-rs/alloy/issues/1728

we can improve this by adding additional trace function that deserialize into the requested frame type

https://github.com/alloy-rs/alloy/blob/36b09310beb27e514df03faf4269aaf55d90a49f/crates/provider/src/ext/debug.rs#L65-L69

e.g.:

```rust
    async fn debug_trace_transaction_as<T>(
        &self,
        hash: TxHash,
        trace_options: GethDebugTracingOptions,
    ) -> TransportResult<T>;

    async fn debug_trace_transaction_js(
        &self,
        hash: TxHash,
        trace_options: GethDebugTracingOptions,
    ) -> TransportResult<serde_json::Value>;


    async fn debug_trace_transaction_call(
        &self,
        hash: TxHash,
        trace_options: GethDebugTracingOptions,
    ) -> TransportResult<CallFrame>;
```

**Comment by loocapro** [comment]
On it!
