### ISSUE TITLE
[Feature] Catch all for extra data in block headers

### ISSUE THREAD

**Issue by onbjerg** [alloy-rs/alloy#18]
### Describe the feature you would like

Foundry has some special handling for some L2s (e.g. Arbitrum), and we use a catch all/fallback field in the block header to look up extra properties on these L2s. This is both used in the forking backend ([here](https://github.com/foundry-rs/foundry/blob/1c7bf46cdf267f06caba6e063329c6ce8f5c914a/crates/evm/core/src/utils.rs#L162-L168)) and in Cast (to show all fields in e.g. `cast block`)

**Comment by prestwich** [comment]
is it sufficient to do something like 
```
struct WithExtraData<T> { 
    inner: T,
    extra: HashMap<String, Value>,
}
```

**Comment by DaniPopes** [comment]
RPC types Block has an `other: OtherFields` field: https://github.com/alloy-rs/alloy/blob/42594c2dfadd07a38139f4a70935c538a9305023/crates/rpc-types/src/eth/block.rs#L40
I believe this is done now.
