### ISSUE TITLE
[Bug]  WASM compilation failure with alloy due to `mio` & `blst` for a bundler target

### ISSUE THREAD

**Issue by Dhruv-2003** [alloy-rs/alloy#1815]
### Component

other

### What version of Alloy are you on?

alloy v0.6.4

### Operating System

macOS (Apple Silicon)

### Describe the bug

When trying to compile my project [Pipegate](https://github.com/Dhruv-2003/pipegate/tree/wasm/core/server) for the `wasm32-unknown-unknown` target with wasm-pack, I encounter error caused by the `mio` & `blst` crates. `mio` seems to be included via `alloy-transport` via tokio. I have already refactored my code for conditional dependencies and change for wasm target, alloy is the dependency which seems to be causing this.

The issue occurs in there scenarios:
1. `wasm-pack build --target=bundler`
- Both `mio` and `blst` fail

2. `wasm-pack build`
- Only `blst` fail

The code I am executing this on can be found [here](https://github.com/Dhruv-2003/pipegate/tree/wasm/core/server) on `wasm` branch

### Error Logs

```
Some errors have detailed explanations: E0308, E0412, E0425, E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `mio` (lib) due to 47 previous errors
warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: blst@0.3.13: error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown"'
warning: blst@0.3.13: 1 error generated.

error: failed to run custom build command for `blst v0.3.13`
```

### Environment 

- rustc 1.82.0 
- wasm-pack 0.12.1

I can share the full log or dependency tree if required

**Comment by gakonst** [comment]
any reason why you cannot disable these features?

**Comment by Dhruv-2003** [comment]
i couldn't figure out which features to include for wasm compatiblity, and i was using `alloy-transport` where mio comes in from as well, so figured that wouldn't help.

will try again to selectively import the features I need

**Comment by Dhruv-2003** [comment]
That worked, thanks! I disabled the default-features and explicitly selected these features `["contract","signer-local","provider-http","reqwest"] ` 

One small suggestion: it would be helpful to have a WASM compatibility mentioned somewhere in the docs for the features, as it could save some time for others working with it
