### ISSUE TITLE
[Feature] EIP4844 tx network encoding support

### ISSUE THREAD

**Issue by montekki** [alloy-rs/alloy#191]
### Component

network, json-rpc

### Describe the feature you would like

Hi everyone, it is great to see 4844 tx support finally land in #185 . I may be missing something but looks like the encoding of the tx together with the tx sidecar for actually submitting such a transaction to the network is currently not implemented? Something alike `reth`'s [blob tx sidecars](https://github.com/alloy-rs/alloy/pull/185)? The testcase only includes the decoding of the transactions as they are on EL (no blobs).

The whole encoding of the tx + blobs for networking is described in https://eips.ethereum.org/EIPS/eip-4844#networking.

Would be great to have support for it!

**Comment by Evalir** [comment]
ref #239

**Comment by prestwich** [comment]
I believe this was closed by #239
