### ISSUE TITLE
[Feature] Deduplicate consensus and rpc types AccessList

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/alloy#255]
### Component

consensus, eips, genesis, network, json-rpc

### Describe the feature you would like

https://github.com/alloy-rs/alloy/blob/b370cf390e88f893711b1dedd90dd7654846e73a/crates/eips/src/eip2930.rs#L47

https://github.com/alloy-rs/alloy/blob/b370cf390e88f893711b1dedd90dd7654846e73a/crates/rpc-types/src/eth/transaction/access_list.rs#L17

**Comment by mattsse** [comment]
from reth POV I believe there's a similar problem with the Withdrawal type, 

so I think we should find a way to extract the Withdrawal type from rpc and perhaps also move to eip crate or find a better location for these types that have the same representation in rpc and consensus

**Comment by sambacha** [comment]
Checking out the access list generation, it seems there are no checks against preventing that \`tx sender\`, \`tx recipient\`, \`block producer\`, created contracts and precompiles  should \*not\* be included in access lists as they are considered warm. Should I make a separate issue?

**Comment by sambacha** [comment]
Checking out the access list generation, it seems there are no checks against preventing that \`tx sender\`, \`tx recipient\`, \`block producer\`, created contracts and precompiles  should \*not\* be included in access lists as they are considered warm. Should I make a separate issue?

**Comment by sambacha** [comment]
Checking out the access list generation, it seems there are no checks against preventing that \`tx sender\`, \`tx recipient\`, \`block producer\`, created contracts and precompiles  should \*not\* be included in access lists as they are considered warm. Should I make a separate issue?

**Comment by DaniPopes** [comment]
I don't fully understand your comment but that should definitely be in a different issue

**Comment by mattsse** [comment]
from,to are excluded

https://github.com/paradigmxyz/evm-inspectors/blob/d7317c7fbf38d5e5df2393beee0414c987ea440a/src/access_list.rs#L31

**Comment by mattsse** [comment]
AccessList+Withdrawals should be moved to eips crate

**Comment by JackG-eth** [comment]
Happy to pick this up
