### ISSUE TITLE
[Feature] Add network-parameterized block responses

### ISSUE THREAD

**Issue by onbjerg** [alloy-rs/alloy#267]
### Component

network, json-rpc, providers, pubsub

### Describe the feature you would like

#190 replaced the provider with a network-parameterized provider, but block responses are still just Ethereum headers and Ethereum transactions. We need a `Block` type generic for networks.

We have one in `alloy-network` but we need to check that it is correct and use it in `alloy-providers`:

https://github.com/alloy-rs/alloy/blob/63af0c4dd43a94126348afaf94b744b98608c293/crates/network/src/lib.rs#L36-L51

**Comment by leruaa** [comment]
#383 follow up: Remove the lines below and wrap `Block` in `WithOtherFields<Block>` instead
https://github.com/alloy-rs/alloy/blob/28cab90c70ef2df16571e1ec131aebbba7bc4412/crates/rpc-types/src/eth/block.rs#L962-L963

**Comment by leruaa** [comment]
Btw I would like to take this on once #383 is merged.
