### ISSUE TITLE
[Feature] Add `block_time_f64` to `Anvil`

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/alloy#285]
### Component

nodes

### Describe the feature you would like

https://github.com/foundry-rs/foundry/pull/7380

This must be a separate method to not break the API, and also older versions will not support it

**Comment by lakshya-sky** [comment]
Hello @DaniPopes, this is my first time opening a PR for alloy, I did my best to come up with a solution without changing too much code. If you think that we should have separate fields please let me know I would appreciate the nudge in correct direction.
