### ISSUE TITLE
[Feature] Collapse `AnvilProvider` into `Provider`

### ISSUE THREAD

**Issue by onbjerg** [alloy-rs/alloy#286]
### Component

provider, pubsub

### Describe the feature you would like

No need for the extension trait

**Comment by moricho** [comment]
Hi, @onbjerg. I've just seen the issue https://github.com/alloy-rs/alloy/issues/271, is my understanding correct that there are plans to remove `AnvilProvider` and incorporate Anvil-specific RPC methods such as `anvil_setCode` into the standard Provider trait using `#[cfg(feature = "anvil")]` or a similar approach?

**Comment by moricho** [comment]
Understood! Thanks
