### ISSUE TITLE
[Feature] Add standalone HttpError response error type

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#288]
### Component

rpc

### Describe the feature you would like

https://github.com/alloy-rs/alloy/blob/09e90e8a76542aaffb3ac0c551a678f2e4fa2890/crates/transport-http/src/hyper.rs#L43-L47

this makes it very hard to check for HTTP errors for things like retry:

https://github.com/foundry-rs/foundry/pull/7384

## TODO
add a standalone `Error` struct so we can try downcasting this from the Custom variant, though perhaps this should even be its own variant

FYI: @zerosnacks

**Comment by prestwich** [comment]
should this be done in a separate PR, as retry layer seems pretty big and a ways off from completion
