### ISSUE TITLE
[Feature] Make provider polling interval configurable

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/alloy#290]
### Component

provider, pubsub

### Describe the feature you would like

Should be a method in both `RootProvider` and `RpcClient`

https://github.com/alloy-rs/alloy/blob/512e15f23648726ddf5262804ac16eb51664cef2/crates/rpc-client/src/client.rs#L167

**Comment by prestwich** [comment]
closed by #437 and #767
