### ISSUE TITLE
[Feature] Provider::connect API

### ISSUE THREAD

**Issue by yash-atreya** [alloy-rs/alloy#318]
### Component

provider, pubsub

### Motivation

Currently the DX of instantiating `Provider`'s is cumbersome. 

In order to initialize a simple `HttpProvider` a user needs to do the following: 
`RpcClient` which needs a `Transport` type (http / ws)  which needs a reqwest client. 

We also need to specify the `Network` as a generic.

```rust
fn init() -> (HttpProvider<Ethereum>, AnvilInstance) {
    let anvil = Anvil::new().fork("https://eth.merkle.io").spawn();
    let url = "https://eth.merkle.io".parse().unwrap();
    let http = Http::<Client>::new(url);
    (HttpProvider::new(RpcClient::new(http, true)), anvil)
}
```

The above applies to instantiating WS and IPC providers as well.

### Solution

Implement a simpler API such that a user can just pass a RPC_URL (http/ws) or IPC_PATH and a provider is generated accordingly. 

Ideal interface to achieve this UX is implementing a `connect` method in `Provider` that accepts a `String` or `Url` type and returns a `Provider`.

```rust
let http_provider = Provider::connect("http://eth.merkle.io")
let ws_provider = Provider::connect("was://eth.ws-provider.io")
let ipc_provider = Provider::connect("/tmp/reth.ipc")
```

**Comment by prestwich** [comment]
```
let http_provider = Provider::connect("http://eth.merkle.io")
let ws_provider = Provider::connect("was://eth.ws-provider.io")
let ipc_provider = Provider::connect("/tmp/reth.ipc")
```

this is not an achievable API unless the type of all 3 contains `BoxTransport` instead of the actual transport types.

**Comment by DaniPopes** [comment]
@prestwich `ProviderBuilder::connect -> Provider<BoxedTransport>`?

**Comment by prestwich** [comment]
not a good api, because that would lead to users using the connect function, and then accidentally blowing up their alchemy bill via polling instead of subscribing over ws. We need to force the user to know their transport type, unless they're specifically intending to box it.

**Comment by yash-atreya** [comment]
> not a good api, because that would lead to users using the connect function, and then accidentally blowing up their alchemy bill via polling instead of subscribing over ws. We need to force the user to know their transport type, unless they're specifically intending to box it.

To that point, we could have `Provider::connect_http(&str) -> RootProvider<BoxedTransport>` and it would still be better than what it is right now and also force the users to know what they are using.

Similarly also have `connect_ws` and `connect_ipc`. All use a non-public `Provider::connect` fn under the hood. We just parse the string to enforce the type of connection. 

Is this possible?

**Comment by DaniPopes** [comment]
Both things can be true, we can have a `connect` API for the common case of CLI URL -> Provider type with a nice error message if the feature is not enabled, and we can also have individual for each type that a user may want to instantiate.

**Comment by prestwich** [comment]
The problem arises because the connect return type will not be pub regardless of the argument to connect indicates pub sub. Which means that users, intending to instantiate a pub sub will use the connect interface, and fail to do so. This API is a footgun

**Comment by DaniPopes** [comment]
No, it's not, I've implemented subscription APIs with this in mind, if `BoxTransport`'s underlying type is `PubsubFrontend` it also works.
Even if that were true, we would want to make it work rather than dismissing it because the current implementation would make it a footgun.
