### ISSUE TITLE
transaction_type could be None in old transaction receipt

### ISSUE THREAD

**Issue by jonathanpwang** [alloy-rs/alloy#327]
https://github.com/alloy-rs/alloy/blob/410850b305a28297483d819b669b04ba31796359/crates/rpc-types/src/eth/transaction/receipt.rs#L53

This should be `Option<U8>` to account for legacy transactions?

**Comment by mattsse** [comment]
the comment is just wrong, legacy transactions are simply 0x0, ref #329
