### ISSUE TITLE
[Suggestion] Change `nonce` field to be `u64` compatible

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/alloy#335]
### Component

provider, pubsub

### Describe the feature you would like

Instead of `.nonce(U64::from(1))` we would want to be able to do just `.nonce(1)`.

See: https://github.com/alloy-rs/examples/pull/2#discussion_r1526812484
See: https://github.com/alloy-rs/examples/pull/2#discussion_r1526813443
See: https://github.com/alloy-rs/examples/pull/8#discussion_r1526788047

There are likely also other places where similar user facing values are desired to be native types: 

- `chain_id`
- `transaction_type`
- etc..

See: https://github.com/alloy-rs/examples/pull/2#discussion_r1526813443

### Additional context

Once implemented make sure to fix in examples: https://github.com/alloy-rs/examples/pull/2

There is some complexity around this, FWD from @prestwich in https://github.com/alloy-rs/examples/pull/8#discussion_r1528910529:

>rpc types must store nonce as U64 (or use a serde(with = ...)) to be on-spec so this probably propagates outward from there 😮‍💨 we should settle on a specific type for these and audit codeplace for compliance. prefer u64 in all non-rpc structs

**Comment by mattsse** [comment]
yeah, we def want this, because usually the input is primitive u64, and it's easier to go form U64 to u64

**Comment by zerosnacks** [comment]
> yeah, we def want this, because usually the input is primitive u64, and it's easier to go form U64 to u64

Added an initial implementation here, uses the `u64_hex_or_decimal` / `u64_hex_or_decimal_opt` functions to handle the RPC structs
