### ISSUE TITLE
[Feature] Move Mainnet KZG group and `Lazy<KzgSettings>`

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#349]
### Component

consensus, eips, genesis

### Describe the feature you would like

4844 constants in alloy-eips needs the following
- KZG constants and files from [revm-primitives](https://github.com/bluealloy/revm/tree/main/crates/primitives/src/kzg)
- `Lazy<Arc<KzgSettings>>` and other loading methods from [reth](https://github.com/paradigmxyz/reth/blob/c868c52063a7f507f2a455a752e159c9b5f08402/crates/primitives/src/constants/eip4844.rs#L8)

### Additional context

Should be feature-gated behind `c_kzg`

**Comment by developeruche** [comment]
```rust 
#[cfg(feature = "kzg")]
use c_kzg::{Blob, Bytes48, KzgCommitment, KzgProof, KzgSettings};
```

this is already behind the`kzg` features flag, do you intend the feature should be changed to `c_kzg`?

**Comment by prestwich** [comment]
no, use whatever existing feature name 🤝

**Comment by developeruche** [comment]
I don't think, 

1. [g1_points](https://github.com/bluealloy/revm/blob/main/crates/primitives/src/kzg/g1_points.bin)
2. [g2_points](https://github.com/bluealloy/revm/blob/main/crates/primitives/src/kzg/g2_points.bin)
3. [trusted_setup](https://github.com/bluealloy/revm/blob/main/crates/primitives/src/kzg/trusted_setup.txt)

would be necessary in the `alloy-eips` module, what do you think?

Secondly, I am looking to add;

1. Re-export `EnvKzgSettings` from the `revm-primitive` env_settings.rs
2. Re-export all public const from `revm-primitive` trusted_setup_points.rs


what are your thoughts?

**Comment by developeruche** [comment]
@prestwich

**Comment by mattsse** [comment]
all of the utils and constants defined on revm should be moved here, then once we have a release we can replace them in revm with our crate

**Comment by developeruche** [comment]
Alright... that makes sense
