### ISSUE TITLE
[Doc] Document special treatment of 1559 in provider and layers

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#371]
we need to write down somewhere that 1559 is somewhat privileged by the library in ways that other tx types and HF features are not. I.e. we generally assume that 1559 is active and proactively attempt to use it in gas estimation even tho we acknowledge that there may be chains that don't support it

_Originally posted by @prestwich in https://github.com/alloy-rs/alloy/pull/363#discussion_r1535775698_

**Comment by developeruche** [comment]
Do you think it is cool to drop this context [here](https://github.com/alloy-rs/alloy/blob/main/README.md)

**Comment by onbjerg** [comment]
@developeruche we want to document it in the code where this is the case so it shows up on docs.rs, so e.g. in the call builder
