### ISSUE TITLE
[Feature] Add Http::new for reqwest::Client

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#387]
### Component

rpc

### Describe the feature you would like

the most commonly used http transport is reqwest::Client, currently it's required to provide the type:

 `let http = Http::<Client>::new(url);`

this requires to always pull in reqwest.

I think it would be reasonable to move the `new` function to `impl Http<reqwest::Client>`, there is already `Http::with_client` that is sufficient for all other use cases.

**Comment by nkysg** [comment]
I can try this.
