### ISSUE TITLE
[Feature] encodable/decodable for Signed transaction

### ISSUE THREAD

**Issue by allnil** [alloy-rs/alloy#398]
### Component

consensus, eips, genesis

### Describe the feature you would like

alloy-consensus:
e.g: usual TxEip4844 implements Encodable/Decodable 
But Signed doesn't
we should have the ability to encode/decode Signed transactions directly

### Additional context

e.g at this moment we can't do this:
```                            
let mut encoded = Vec::new();
my_tx.encode_for_signing(&mut encoded);
let signature = local_wallet.sign_signable(&mut my_tx.clone()).unwrap();
let mut signed_tx = my_tx.clone().into_signed(signature);
let encoded = &alloy_rlp::encode(signed_tx); // trait `Encodable` is not implemented for `Signed<TxEip4844>` 
 ```

https://github.com/alloy-rs/alloy/blob/f7333c4344fdf6a16f620bc4392ba81b64684017/crates/consensus/src/signed.rs#L6

we want the Encodable2718 trait, impl in TxEnvelope:
https://github.com/alloy-rs/alloy/blob/f7333c4344fdf6a16f620bc4392ba81b64684017/crates/consensus/src/transaction/envelope.rs#L216-L216

**Comment by mattsse** [comment]
@prestwich I think what we want is 

https://github.com/alloy-rs/alloy/blob/f7333c4344fdf6a16f620bc4392ba81b64684017/crates/eips/src/eip2718.rs#L124-L124

for `Signed<Tx>`

we could either do this manually or make this 

https://github.com/alloy-rs/alloy/blob/f7333c4344fdf6a16f620bc4392ba81b64684017/crates/consensus/src/transaction/envelope.rs#L230-L243

part of a trait, so we can do:

https://github.com/alloy-rs/alloy/blob/f7333c4344fdf6a16f620bc4392ba81b64684017/crates/consensus/src/signed.rs#L34-L34

**Comment by onbjerg** [comment]
You can do this by wrapping it in an envelope which IIRC was intended, I vaguely remember the blanket impl for `Signed<Tx>` being removed by @Rjected in a recent PR

**Comment by allnil** [comment]
Hmmm, okay! I'll take a look into the TxEnvelope
Thank you
