### ISSUE TITLE
Dedupe blob transaction sidecar

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#400]
Can we proactively dedupe this as part of this PR?

current code in RPC types is as follows
```
/// This represents a set of blobs, and its corresponding commitments and proofs.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[repr(C)]
pub struct BlobTransactionSidecar {
    /// The blob data.
    pub blobs: Vec<Blob>,
    /// The blob commitments.
    pub commitments: Vec<Bytes48>,
    /// The blob proofs.
    pub proofs: Vec<Bytes48>,
}
```

_Originally posted by @prestwich in https://github.com/alloy-rs/alloy/pull/361#discussion_r1540035588_

**Comment by mattsse** [comment]
kzg validation only works with kzg bytes and blob types.

we can dedup but this means we have c-kzg dep no longer optional because we need the sidecar for all things rpc, we could however remove the sidecar type with c-kzg and transmut when calling validate? so that we don't use c-kzg types at all

**Comment by prestwich** [comment]
Kzg validation shouldn't occur unless the kzg feature flag is on, no?
