### ISSUE TITLE
[Debt] remove type switching on kzg feature

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#402]
### Component

consensus, eips, genesis

### Operating System

None

### Describe the bug

consensus and engine-types switch the `Blob` and `Bytes48` types when the `kzg` feature is enabled. These types are props in `BlobTransactionSidecar` `SidecarBuilder` and `BlobsBundleV1` and create problems with RLP and SSZ impls on those types.

Instead of switching when the feature is enabled, we should transmute when and only when doing KZG operations

**Comment by developeruche** [comment]
Additional context:

```rust 

#[cfg(not(feature = "kzg"))]
use alloy_eips::eip4844::Blob;
#[cfg(feature = "kzg")]
use c_kzg::{Blob, KzgCommitment, KzgProof};

```

from: https://github.com/alloy-rs/alloy/blob/15d56f959f64dc103918166a66ac93ad1ea3af4d/crates/consensus/src/transaction/eip4844/builder.rs#L1C1-L4C44


another:

**Comment by developeruche** [comment]
I would like to take on this

**Comment by developeruche** [comment]
this is how my implementation is going, It is looking messy, I guess I am doing something wrong;

```rust 

    pub fn with_capacity(capacity: usize) -> Self {
        let mut blobs = Vec::with_capacity(capacity);
        #[cfg(feature = "kzg")]
        use c_kzg::{Blob};
        #[cfg(feature = "kzg")]
        let blobs: Vec<Blob> = unsafe { std::mem::transmute(blobs) };
        
        blobs.push(Blob::new([0u8; BYTES_PER_BLOB]));
        Self { blobs, fe: 0 }
    }

```


@prestwich what are your thoughts?
