### ISSUE TITLE
[Feature] Complete `Receipt` type

### ISSUE THREAD

**Issue by tcoratger** [alloy-rs/alloy#408]
### Component

consensus, eips, genesis

### Describe the feature you would like

As per https://github.com/paradigmxyz/reth/issues/7238, our current `Receipt` structure in Alloy:

https://github.com/alloy-rs/alloy/blob/main/crates/consensus/src/receipt/receipts.rs

is not complete regarding what we have in reth:

https://github.com/paradigmxyz/reth/blob/1a7ba845b2ed623699a04031919c7e6479f39dc9/crates/primitives/src/receipt.rs

As a result, we should complete the `Receipt` type in alloy, in order to use it as a primitive type and remove its definition from reth. In my opinion, we should also add here the missing structures that are used around such as `Receipts` (which represents a two dimensional vector of `Receipt`) or `ReceiptWithBloomEncoder`.

As a consequence, to be able to handle `root_slow` properly, we should also add a proof crate or something related.

**Comment by prestwich** [comment]
when you say it isn't complete, what do you mean? This is the consensus receipt type, and doesn't need anything else to be complete

**Comment by tcoratger** [comment]
> when you say it isn't complete, what do you mean? This is the consensus receipt type, and doesn't need anything else to be complete

I think that we miss here:
- TxType
- Optimism cfg features
- `Receipts` two dimensional vector
- `root_slow`
- `optimism_root_slow`
- `gas_spent_by_tx`
- ...

Maybe some of these functions don't have their place in consensus types, but it wouldn't be bad to integrate them into alloy in order to remove the (a little redundant) definition that is in reth and only import the primitive types around the `Receipt` from alloy in reth right? Maybe somewhere else?

**Comment by prestwich** [comment]
> TxType

use `ReceiptEnvelope`

> Optimism cfg features

Out of scope. this crate is for Ethereum consensus. Alloy approach would be a new `OptimismReceiptEnvelope` type in an alloy-consensus-optimism crate in another workspace

> `bloom_slow`

yeah, this is probably a good addition

> `root_slow`

seems like a property of a container type that belongs in reth?

**Comment by mattsse** [comment]
> is not complete regarding what we have in reth:

I think this is complete, at least if the enveloped type is used, which encodes/decodes to/from the wire format:

https://github.com/ethereum/devp2p/blob/master/caps/eth.md#receipt-encoding-and-validity

for op this should be a separate type

**Comment by prestwich** [comment]
closing as complete based on discussion above
