### ISSUE TITLE
[Bug] Fix unknown/unused `cfg`s

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/alloy#416]
### Component

consensus, eips, genesis

### Operating System

None

### Describe the bug

`cargo check -Zcheck-cfg` reports a lot of unexpected cfg values. Consider also adding this to CI.

**Comment by DaniPopes** [comment]
cc @yash-atreya

**Comment by yash-atreya** [comment]
@developeruche 
> Could you help me with a reference to creating an RpcClient using the Http as the transport layer

If you've enabled the `reqwest` feature on `alloy-rpc-client` then you can do the following to instantiate a `RpcClient<Http<Client>>`:

```rust
let client = Rpc<Http<Client>>::new_http(URL);
```

Also can you please share which version of alloy you're using i.e the commit hash you're pinned to?

**Comment by developeruche** [comment]
> > hey @DaniPopes, on enabling the "reqwest" feature
> > ```rust
> >  #[cfg(feature = "reqwest")]
> >     pub fn reqwest_http(self, url: url::Url) -> TransportResult<RpcClient<L::Service>>
> >     where
> >         L: Layer<alloy_transport_http::Http<reqwest::Client>>,
> >         L::Service: Transport,
> >     {
> >         let transport = alloy_transport_http::Http::new(url);
> >         let is_local = transport.guess_local();
> > 
> >         Ok(self.transport(transport, is_local))
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am get this error;
> > crates/provider/src/builder.rs:236:27 | 236 | Ok(self.on_client(client)) | --------- ^^^^^^ expected `RpcClient<BoxTransport>`, found `RpcClient<Http<Client>>` | | | arguments to this method are incorrect | = note: expected struct `RpcClient<BoxTransport>` found struct `RpcClient<alloy_transport_http::Http<Client>>`
> > Could you help me with a reference to creating an `RpcClient` using the Http as the transport layer
> > cc: @DaniPopes
> 
> @developeruche Implemented a fix here: #419

Awesome 🙌
