### ISSUE TITLE
[Feature] Add `blockTimestamp` field to Log type

### ISSUE THREAD

**Issue by cairoeth** [alloy-rs/alloy#422]
### Component

rpc

### Describe the feature you would like

Unblock [6752](https://github.com/paradigmxyz/reth/issues/6752) from reth:

> The proposed enhancement to include a blockTimestamp field in the eth_getLogs response is a pragmatic approach to solving a significant efficiency problem faced by Ethereum applications. It streamlines the process of fetching event data with timestamps, which is critical for many blockchain-based applications.

Potential breaking change if the field is not optional.

**Comment by mattsse** [comment]
> Potential breaking change if the field is not optional.

we should make this optional and skip if missing
