### ISSUE TITLE
Improve tx request builder

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#423]
while we're touching this code, we should decompose this into a set of functions `fn will_build_legacy() -> bool` that capture our criteria for building each style of transaction. then this becomes a fallthrough if

I also think our criteria here are not most-friendly to users.

- if a sidecar is set, we should ALWAYS build 4844, regardless of if legacy gas is indicated
- if `max_fee_per_blob_gas` is set, but no sidecar/blob is set, that should be a build error
- if `access_list` is set, we should ALWAYS build 2930, regardless of if legacy gas is indicated
- if `sidecar` and `access_list` are both set throw a build error
- 1559 should be our default tx type in the fallthrough case. legacy should be chosen only if gas_price is set.

function should look something as follows:
```
if self.will_build_4844() { self.build_4844() } 
else if self.will_build_2930() { self.build_2930() }
else if self.will_build_legacy() { self.build_legacy() }
else { self.build_1559() } 
```

_Originally posted by @prestwich in https://github.com/alloy-rs/alloy/pull/383#discussion_r1544689297_

**Comment by mattsse** [comment]
> 1559 should be our default tx type in the fallthrough case. legacy should be chosen only if gas_price is set.

agree

**Comment by leruaa** [comment]
I can work on this.
