### ISSUE TITLE
[Feature] Typed transaction conversion traits 

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#438]
### Component

consensus, eips, genesis

### Describe the feature you would like

blocked by #433 

add standard conversions to transaction types

- [ ] modify `Network` 
    - [ ] add a new bound: `type UnsignedTx: From<Self::TxEnvelope>`
    - [ ] add 2 new bounds: `type TransactionRequest: From<Self::TxEnvelope> + From<Self::UnsignedTx>`
- [ ] satisfy new bounds
    - [ ] `impl From<TxEnvelope> for TypedTransaction`
    - [ ] `impl From<TxEnvelope> for TransactionRequest`
    - [ ] `impl From<TypedTransaction for TransactionRequest`

**Comment by mahmudsudo** [comment]
can i take on this ?

**Comment by siosw** [comment]
I think this has been completed in #472 should be closed

**Comment by mattsse** [comment]
yep
