### ISSUE TITLE
[Bug] Dedupe `alloy_network::TransactionList` and `alloy_rpc_types::BlockTransactions`

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#440]
### Component

consensus, eips, genesis, network, json-rpc

### Operating System

None

### Describe the bug

Related to #439 

These types are duplicated

**Comment by yash-atreya** [comment]
TransactionList is in `alloy_network

**Comment by prestwich** [comment]
my bad 😅

**Comment by yash-atreya** [comment]
Can be closed #444
