### ISSUE TITLE
[Bug] Dedupe `alloy_consensus::BlockResponse<N>` and `alloy_rpc_types::Block`

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#441]
### Component

consensus, eips, genesis, network, json-rpc

### Operating System

None

### Describe the bug

related to #440 

These types are duplicated, but block response is unused. 

cc @mattsse will all sane networks use the same pattern for block responses? flattened header + transactions + other fields?

**Comment by yash-atreya** [comment]
Can be closed #444
