### ISSUE TITLE
[Feature]  Add function to derive the func name and other details of a function call given a raw tx + abi

### ISSUE THREAD

**Issue by 0xFloop** [alloy-rs/alloy#473]
### Component

rpc

### Describe the feature you would like

Correct me if I am wrong as I am a novice in rust, but whilst trying to rewrite a ts back-end to rust wherein I was using Viem to convert a raw tx to its components and then derive the function name being called given the abi, I could not seem to find methods to do so easily. I wrote a simple function to  complete this task of rawtx+abi->function details and am wondering if that would be something that you think alloy could use, if so I would be happy to tighten it up and open a pr. Thanks and let me know if I just missed this feature somewhere!

**Comment by prestwich** [comment]
this functionality is provided by [alloy-json-abi](https://docs.rs/alloy-json-abi/0.7.4/alloy_json_abi/) and [alloy-dyn-abi](https://docs.rs/alloy-dyn-abi/0.7.4/alloy_dyn_abi/), which are part of the [alloy-rs/core](https://github.com/alloy-rs/core) repo. If you know the ABI at compile time, you can use [alloy-sol-types](https://docs.rs/alloy-dyn-abi/0.7.4/alloy_dyn_abi/) and the `sol!` macro instead for better perf and more ergonomic types
