### ISSUE TITLE
[Feature] RetryBackoffLayer retry layer from foundry

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#490]
### Component

network, json-rpc

### Describe the feature you would like

https://github.com/foundry-rs/foundry/blob/a6d6a3a8f0442adb0162082fdd8e5aaa69287c80/crates/common/src/provider/tower.rs#L22-L22

extract from foundry and add to provider crate

**Comment by prestwich** [comment]
can this be achieved by re-exporting tower layers?

**Comment by mattsse** [comment]
I think so, but imo, it would be useful to have support for compute unit-based retries as a builtin layer

**Comment by prestwich** [comment]
yeah we should definitely port that part
