### ISSUE TITLE
[Feature] Port `ethers-addressbook` to `alloy`

### ISSUE THREAD

**Issue by yash-atreya** [alloy-rs/alloy#503]
### Component

contract, provider, pubsub

### Describe the feature you would like

Port [ethers-addressbook](https://github.com/gakonst/ethers-rs/tree/master/ethers-addressbook) to `alloy`

**Comment by yash-atreya** [comment]
@mattsse @prestwich Supportive? Will be implemented as another crate in alloy.

**Comment by prestwich** [comment]
This has a very low surfsce area but a potentially very high burden of maintenance via update requests. Thinking about whether it should be part of alloy or in a separate utils workspace. Do we know the actual number of ethers PRs that touched the JSON?
