### ISSUE TITLE
[Question] is there a way to rlp::encode rpc::types::TransactionReceipt 

### ISSUE THREAD

**Issue by DylanVerstraete** [alloy-rs/alloy#512]
### Component

rpc

### Operating System

Linux

### Describe the bug

Is there another way to rlp encode `rpc::types::TransactionReceipt` without doing this?

```rs
#[derive(Debug, Clone)]
pub struct Receipt(pub alloy::rpc::types::eth::TransactionReceipt);

impl BlockItem for Receipt {
    fn to_bytes(&self) -> Vec<u8> {
        let rwb = self.0.inner.as_receipt_with_bloom().unwrap();
        let receipt = rwb.receipt.clone();

        let mut new_receipt = alloy::consensus::Receipt::default();
        new_receipt.cumulative_gas_used = receipt.cumulative_gas_used;
        new_receipt.status = receipt.status;
        let logs = receipt
            .logs
            .into_iter()
            .map(|l| {
                let log = Log::new(l.address(), l.topics().to_vec(), l.data().data.clone());
                log.unwrap()
            })
            .collect::<Vec<Log>>();
        new_receipt.logs = logs;

        let rwb_new: ReceiptWithBloom<Log> = ReceiptWithBloom::new(new_receipt, rwb.logs_bloom);
        alloy::rlp::encode(&rwb_new)
    }
```

**Comment by mattsse** [comment]
which alloy rev are you on?

tx receipt now wraps the encodable receipt directly

https://github.com/alloy-rs/alloy/blob/d79cc4a6b828d16774bb4dbab7c5e7714c660c9d/crates/rpc-types/src/eth/transaction/receipt.rs#L18-L18

**Comment by DylanVerstraete** [comment]
```
name = "alloy"
version = "0.1.0"
source = "git+https://github.com/alloy-rs/alloy#cd5a2c7cb10c04e0e0c1a31ff0b5a66a1c1a6740"
```

**Comment by mattsse** [comment]
ah I see the issue, `ReceiptEnvelope<Log>` the log is the rpc log and not the actual log

**Comment by DylanVerstraete** [comment]
Yeah, I can't call the rlp::encode on it cause the log is rpl type log

**Comment by mattsse** [comment]
alternatively, I believe

https://github.com/alloy-rs/alloy/blob/d79cc4a6b828d16774bb4dbab7c5e7714c660c9d/crates/consensus/src/receipt/receipts.rs#L172-L184

can be modified so it works with `T: AsRef<Log>` which should also solve the issue

**Comment by mattsse** [comment]
mind trying this approach?

**Comment by DylanVerstraete** [comment]
See the original comment, I have to construct a `consensus::ReceiptWithBloom` from the rpc one

**Comment by mattsse** [comment]
what you actually want is a way to encode it,
we could either modify the encode impl of the receipt, or add a helper for the tx receipt.

the latter is likely easier, but I think the former would also be possible by changing the T: AsRef<alloy_primitive::Log> on ReceiptEnvelope

**Comment by prestwich** [comment]
capturing some type relationships here for reference while we look at this:

- `rpc::Receipt` extends `consensus::Receipt`
- `rpc::Log<T>` extends `consensus::Log<T>` with extra fields
- `consensus::Receipt` contains EITHER `rpc::Log<T>` or `consensus::Log<T>`
- `consensus::Log<T>` contains EITHER `LogData` or some decoded `SolEvent` type
- `rlp::Encodable` should be implemented for all of the following:
    - `consensus::Log<LogData>`
    - `consensus::Log<T: SolEvent>`
    - `consensus::Receipt<consensus::Log>`
    - `consensus::Receipt<rpc::Log>`
    - `rpc::Log<T>`
    - `rpc::Log<SolEvent>` 
    - `rpc::Receipt`
- `rlp::Decodable` CANNOT be implemented for the the following:
    - `rpc::Log`
    - `rpc::Receipt`

**Comment by mattsse** [comment]
> should be implemented for all of the following

haven't thought about this solution, yes this is indeed the best solution @DylanVerstraete

**Comment by DylanVerstraete** [comment]
Makes sense that `rlp::Encodable` should be implemented to all beforementioned types by @prestwich

**Comment by prestwich** [comment]
made some adjustments to the list to make it clearer :)

The reason decodable cannot be implemented for RPC types is that most information in the RPC type is not committed to in the RLP bytestring for Logs/Receipts

**Comment by DylanVerstraete** [comment]
for transactions encoding I do this right now:

```rs

pub struct Transaction(pub alloy::rpc::types::eth::Transaction);

impl BlockItem for Transaction {
    fn to_bytes(&self) -> Vec<u8> {
        match self.0.transaction_type {
            Some(0) => {
                let tx: Signed<TxLegacy> = self.0.clone().try_into().unwrap();
                alloy::rlp::encode(tx.into_parts().0)
            }
            Some(1) => {
                let tx: Signed<TxEip1559> = self.0.clone().try_into().unwrap();
                alloy::rlp::encode(tx.into_parts().0)
            }
            Some(2) => {
                let tx: Signed<TxEip2930> = self.0.clone().try_into().unwrap();
                alloy::rlp::encode(tx.into_parts().0)
            }
....
```

**Comment by prestwich** [comment]
related to #623

**Comment by prestwich** [comment]
closing this issue in favor of #623, as it captures the remaining work. @DylanVerstraete please let us know if any specific use that isn't currently achievable
