### ISSUE TITLE
[Feature] Change all `Option<BlockId>` to `BlockId` on methods in the `Provider`

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/alloy#514]
### Component

provider, pubsub

### Describe the feature you would like

`get_code_at` and `get_uncle` on the `Provider` currently require the user to define the `tag` whereas others allow for defining `tag` as `None`, where `None` means defaulting to `Latest`.

https://github.com/alloy-rs/alloy/blob/7629f79e3ffb6abd0be901a06deed2ab9f695e4e/crates/provider/src/provider.rs#L768-L771

https://github.com/alloy-rs/alloy/blob/7629f79e3ffb6abd0be901a06deed2ab9f695e4e/crates/provider/src/provider.rs#L826-L836

Whereas other methods allow for defining `tag` as `None`, 

https://github.com/alloy-rs/alloy/blob/7629f79e3ffb6abd0be901a06deed2ab9f695e4e/crates/provider/src/provider.rs#L627-L639

Where automatically defaulting means `Latest`:

https://github.com/alloy-rs/alloy/blob/987b3936f78c067baedcf811620975d3a4a26443/crates/rpc-types/src/eth/block.rs#L719-L723

Based on feedback from @mattsse on the PR of @EmperorOrokuSaki it was decided to instead of making `get_code_at` and `get_uncle` have `Option<BlockId>` to change all other methods to use `BlockId` (not optional).

**Comment by EmperorOrokuSaki** [comment]
I'll work on this.

**Comment by zerosnacks** [comment]
> Hey, update on this. The direction is going to be the removal of all Option params and making them required in provider methods. This ensures consistency with the JSON RPC specification.

Thanks! I'll update the description and title

**Comment by EmperorOrokuSaki** [comment]
Can we close this issue? The PR was merged.
