### ISSUE TITLE
[Feature] `alloy_rpc_types::eth::log::Log` and `Log` have similar names, but are actually distinct types

### ISSUE THREAD

**Issue by NicolasWent** [alloy-rs/alloy#519]
### Component

contract, network, json-rpc

### Describe the feature you would like

Hello,

When we get logs from [TransactionReceipt](https://github.com/alloy-rs/alloy/blob/f44973a0e7c2f9137b762cb5350995ae51c1743f/crates/rpc-types/src/eth/transaction/receipt.rs#L18) It gives us a log that has the type:

alloy_rpc_types::eth::log::Log

But when we want to decode the log using an abi, it asks for a alloy_primitives::Log instead

<details>
  <summary>Example code to illustrate this problem</summary>
  
```rust
use std::env;

use alloy_primitives::{address, b256, utils::format_ether, Address, B256};
use alloy_provider::{Provider, ProviderBuilder};
use alloy_sol_types::{sol, SolEvent};
use eyre::Result;
use IERC20::Transfer;

const WETH: Address = address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2");

// Transfer topic:
// https://etherscan.io/tx/0xd183a55586addbce7a6c1e3849d495a8dca5a0c8d5f96e876d25dc50bd97c27a#eventlog
const TRANSFER_TOPIC: B256 =
    b256!("ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef");

sol!(
    #[sol(rpc)]
    IERC20,
    "src/abi/IERC20.json"
);

// We know that at least one WETH transfer hapenned at this block:
// https://etherscan.io/tx/0xd183a55586addbce7a6c1e3849d495a8dca5a0c8d5f96e876d25dc50bd97c27a
const BLOCK: u64 = 19633475;

#[tokio::main]
async fn main() -> Result<()> {
    let http_rpc = env::var("HTTP_RPC")?.parse()?;
    let provider = ProviderBuilder::new().on_http(http_rpc)?;
    let receipts = provider
        .get_block_receipts(BLOCK.into())
        .await?
        .expect(&format!("Block {BLOCK} should already exists"));

    for receipt in receipts {
        for log in receipt.inner.logs() {
            if log.address() == WETH {
                if log.topics()[0] == TRANSFER_TOPIC {
                    // here got error: `alloy_rpc_types::eth::log::Log` and `Log` have similar names, but are actually distinct types
                    let transfer = Transfer::decode_log(log, true)?;
                    println!(
                        "{:?} has transfered {} ETH at transaction {:?} to {:?}",
                        transfer.data.src,
                        format_ether(transfer.data.wad),
                        receipt.transaction_hash,
                        transfer.data.dst
                    );
                }
            }
        }
    }

    Ok(())
}
```
</details>

The current workaround is to manually convert:
```rust
let log_primitive = Log::new(
    log.address(),
    log.topics().to_vec(),
    log.data().data.clone(),
)
.unwrap();
```

But that is not very user friendly

#50 should have given a cleaner workaround but I was not able to use it in the latest branch.

I also have a question about this:
I think there is a good reason behind it, but why are there two different `Log` that exists:
`alloy_rpc_types::eth::log::Log` and `alloy_primitives::Log`?

### Additional context

I placed my issue in `features` because I think that adding an easy way to convert from the two different log instance could be helpful

**Comment by mattsse** [comment]
you should be able to do `let transfer = Transfer::decode_log(log.as_ref(), true)?;`

I agree the naming can be confusing,
perhaps we should consider renaming the rpc log type `LogReceipt` or something?

**Comment by prestwich** [comment]
is there a reason that you're not using`log.log_decode<Transfer>()` to manage decoding?

**Comment by prestwich** [comment]
@mattsse I would prefer `RpcLog` and `RpcReceipt` to differentiate

**Comment by NicolasWent** [comment]
Thanks, I didn't found these methods for converting a log, they are way better. I will write an example for these if I have time.

Also why can't RPC directly use the `alloy_primitives::Log`?

**Comment by prestwich** [comment]
> Also why can't RPC directly use the `alloy_primitives::Log`?

Because the RPC Log contains a lot of metadata not found in the consensus Log
