### ISSUE TITLE
[Bug] Can't get block receipts for base

### ISSUE THREAD

**Issue by NicolasWent** [alloy-rs/alloy#528]
### Component

network, json-rpc, rpc

### What version of Alloy are you on?

rev = "8cb0307"

### Operating System

Linux

### Describe the bug

I am trying to get the block receipt of a Base block.

Here is the code to reproduce:

```rust
use alloy_provider::{Provider, ProviderBuilder};
use eyre::Result;

#[tokio::main]
async fn main() -> Result<()> {
    // let provider = ProviderBuilder::new().on_http("https://eth.llamarpc.com".parse()?)?;
    let provider = ProviderBuilder::new().on_http("https://base.gateway.tenderly.co".parse()?)?;

    let receipt = provider
        .get_block_receipts(provider.get_block_number().await?.into())
        .await?;

    println!("{receipt:?}");

    Ok(())
}
```

When I run this code, I am getting the error:
```
Error: deserialization error: unknown variant `0x7e`, expected one of `0x0`, `0x1`, `0x2`, `0x3` at line 1 column 1063

Caused by:
    unknown variant `0x7e`, expected one of `0x0`, `0x1`, `0x2`, `0x3` at line 1 column 1063

Location:
    src/get_receipt.rs:9:19
```

But if I switch to the ethereum mainnet rpc, it works fine

**Comment by DaniPopes** [comment]
The default provider network is Ethereum, which does not include the special type 0x7e (deposit) transactions present in Optimism network.

This will be available in https://github.com/alloy-rs/op-alloy

**Comment by NicolasWent** [comment]
Is it possible to have the default provider supporting everything like it is the case in ethers?

This way, we can make our software support all of the chains just by changing the RPC endpoint and not need any changes in code

**Comment by prestwich** [comment]
> Is it possible to have the default provider supporting everything like it is the case in ethers?

 Use the `AnyNetwork` and report any compatibility issues you encounter as bugs
