### ISSUE TITLE
[Feature] Move BlockId type to alloy-eips

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#535]
### Component

consensus, eips, genesis, rpc

### Describe the feature you would like

BlockId type was introduced in https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1898.md

it'd be beneficial to have this lightweight type in the smaller eips crate than the rpc crate because this type is not only used in rpc.

for example in reth this is part of database provider API.

## TODO

move 

https://github.com/alloy-rs/alloy/blob/8cb0307b9bdb6cef9058d2d1a2219c8d212a7421/crates/rpc-types/src/eth/block.rs#L437-L439

https://github.com/alloy-rs/alloy/blob/8cb0307b9bdb6cef9058d2d1a2219c8d212a7421/crates/rpc-types/src/eth/block.rs#L471-L473

https://github.com/alloy-rs/alloy/blob/8cb0307b9bdb6cef9058d2d1a2219c8d212a7421/crates/rpc-types/src/eth/block.rs#L623-L626

to alloy-eips/src/eip1898.rs

and reexport from rpc crate

**Comment by ThreeHrSleep** [comment]
can take this on :)
