### ISSUE TITLE
[Feature] Add encode/decode for Signed<T: Transaction>

### ISSUE THREAD

**Issue by kayabaNerve** [alloy-rs/alloy#543]
### Component

consensus, eips, genesis

### Describe the feature you would like

To encode a Signed<TxLegacy>, I need to either:

A) Break it into parts and call encode_with_signature_fields
B) Make a TxEnvelope and encode that

Ideally, I could just encode the Signed<TxLegacy> directly. This would presumably be by moving `encode_with_signature_fields` to a trait?

**Comment by prestwich** [comment]
the problem with doing it directly is that the argument to eth_sendRawTransaction is an encoded 2718 envelope, not an encoded signed transaction. It is not recommended to encode a Signed, as there is no endpoint or other behavior that uses that encoding. Using the envelope is always recommended 

what use case are you looking to satisfy by encoding the Signed?

**Comment by mattsse** [comment]
I believe this is relevant here

https://github.com/alloy-rs/alloy/issues/398

**Comment by kayabaNerve** [comment]
Sorry for not realizing this was a duplicated!

I'd like Signed<TxLegacy>::encode to be equivalent to TxLegacy::encode_with_signature_fields. The latter is usable with eth_sendRawTransaction.

**Comment by prestwich** [comment]
also relevant now is #529 which exposed a lot of the inner encoders

> Signed::encode to be equivalent to TxLegacy::encode_with_signature_fields. The latter is usable with eth_sendRawTransaction.

It is usable with `eth_sendRawTransaction` only for legacy transactions, not for any other transaction types. Using it with any other `Signed` would be a logic error and would prevent tx broadcast. So we don't have the API because it's trivially easy to misuse

**Comment by kayabaNerve** [comment]
That clarifies things! Thanks for the context.
