### ISSUE TITLE
[Feature] Add ecrecover

### ISSUE THREAD

**Issue by kayabaNerve** [alloy-rs/alloy#544]
### Component

consensus, eips, genesis

### Describe the feature you would like

alloy itself exposes recover_signer yet not a 1:1 implementation of ecrecover.

ethers-rs did expose a recover function, internally calling the ecdsa crate.

ecdsa doesn't explicitly implement ecrecover, as defined in Ethereum. Please note their policy on low/high s values: https://github.com/RustCrypto/elliptic-curves/issues/991

This did break an EVM dependent on it (which bubbled up into foundry IIRC).

While I could implement ecrecover myself based on ecdsa, I do not want to have to review the ecdsa crate for their current policies/impacted functions. I'd like a function which just works and is guaranteed to work in this context. While I do not believe the ecdsa crate's policies are expected to change, I'll note they require additional code around their recovery in order for their recovery to be used as ecrecover (justifying the definition of a dedicated ecrecover function regardless).

**Comment by DaniPopes** [comment]
This is already implemented in [`alloy_primitives::Signature::recover*`](https://github.com/alloy-rs/core/blob/7e68fa76118d7c138820789efab377174316ca38/crates/primitives/src/signature/sig.rs#L212), see also [this test](https://github.com/alloy-rs/core/blob/7e68fa76118d7c138820789efab377174316ca38/crates/primitives/src/signature/sig.rs#L585) for recovering a non-normalized signature.

**Comment by kayabaNerve** [comment]
Apologies. I looked through the docs and couldn't find it. I don't believe they're generating properly for Signature.

**Comment by DaniPopes** [comment]
Yes you're right, could you open an issue in alloy-rs/core?
