### ISSUE TITLE
[Refactor] change `TransactionRequest` to field to `Option<TxKind>`

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#549]
- [ ] Modify to field to make creates explicit
- [ ] Error on non-4844 build if to is unset
- [ ] Error on 4844 build if to is unset or create
- [ ] Add following to the builder trait
    - [ ] `fn as_create(self) -> Self` shortcut to set the field to `Some(Create)`
    - [ ] `fn deploy_code(self, code: Vec<u8>) -> Self` to set `data` and `to` fields at once
    - [ ] `fn with_call<T: SolCall>(self, t: T) -> Self` to set `data` and ensure `to` is NOT `Create` (set `to` to `None` if it is currently `Create`)

              not convinced we should default to create instead of erroring if not specifically set to create, as creating with `value` and empty data is a valid tx that burns user funds. We should probably error on building if `to` is unset, and provide a shortcut for `.create()`

_Originally posted by @prestwich in https://github.com/alloy-rs/alloy/issues/505#issuecomment-2050124501_

**Comment by EmperorOrokuSaki** [comment]
I'll give this a try.
