### ISSUE TITLE
[Bug]  Newer Git Revisions Of Alloy Don't Work As Expected And Are Unable To Send Transactions

### ISSUE THREAD

**Issue by bonedaddy** [alloy-rs/alloy#554]
### Component

provider, pubsub, signers

### What version of Alloy are you on?

987b3936f78c067baedcf811620975d3a4a26443

### Operating System

Linux

### Describe the bug

While attempting to send a transaction using git commit `987b3936f78c067baedcf811620975d3a4a26443`, I noticed the `Filler`'s were not behaving as expected, in that `nonce`, `gas` and `chain_id` information was not automatically being populated.  I'm more or less using the [examples](https://github.com/alloy-rs/examples) with some minor convenience types. The last git revision I confirmed as working is `bfd0fda`

Attempting to send a transaction using the `Nonce`, `Gas`, and `ChainId` fillers would result in errors being returned that indicate the missing data:

```
MissingKey(
        "nonce",
    )
```

Additionally after manually populating the missing information I would receive this error 

```
 Some(
            RawValue(
                "invalid type: integer `10`, expected a (both 0x-prefixed or not) hex string or byte array containing between (0; 8] bytes at line 1 column 2",
            ),
        ),
```

I have the following code snippets to share

Wrapper types for `Ws` or `RPC` provider that is capable of signing transactions

```rust
pub enum SignerWsOrRpc {
    WS{
        rpc: FillProvider<JoinFill<JoinFill<JoinFill<JoinFill<Identity, GasFiller>, NonceFiller>, ChainIdFiller>, SignerFiller<EthereumSigner>>, RootProvider<PubSubFrontend>, PubSubFrontend, Ethereum>,
        wallet: LocalWallet,
    },
    RPC{
        rpc: FillProvider<JoinFill<JoinFill<JoinFill<JoinFill<Identity, GasFiller>, NonceFiller>, ChainIdFiller>, SignerFiller<EthereumSigner>>, RootProvider<Http<Client>>, Http<Client>, Ethereum>,
        wallet: LocalWallet
    }
}


impl SignerWsOrRpc {
    pub async fn send_transaction(&self, tx: <Ethereum as Network>::TransactionRequest) -> anyhow::Result<FixedBytes<32>> {
        match self {
            Self::WS{rpc, wallet} => {
                let tx = tx.with_chain_id(rpc.get_chain_id().await?).build(&EthereumSigner::from(wallet.clone())).await.with_context(|| "failed to build tx")?;
                Ok(*rpc.send_transaction(tx.into()).await.with_context(|| "failed to send tx")?.tx_hash())
            }
            Self::RPC{rpc, wallet} => {
                let tx = tx.with_chain_id(rpc.get_chain_id().await?).build(&EthereumSigner::from(wallet.clone())).await.with_context(|| "failed to build tx")?;
                Ok(*rpc.send_transaction(tx.into()).await.with_context(|| "failed to send tx")?.tx_hash())
            }
        }
    }
}
```

Function that takes an existing `Provider` and converts it to the wrapper

```rust
    pub fn to_signer(&self, wallet: LocalWallet) -> SignerWsOrRpc {
        match self {
            Self::WS(ws) => {
                SignerWsOrRpc::WS{
                    rpc: ProviderBuilder::new().with_recommended_fillers().signer(EthereumSigner::from(wallet.clone())).on_provider(ws.clone()),
                    wallet
                }
            },
            Self::RPC(rpc) => { 
                SignerWsOrRpc::RPC{
                    rpc: ProviderBuilder::new().with_recommended_fillers().signer(EthereumSigner::from(wallet.clone())).on_provider(rpc.clone()),
                    wallet
                }
            }
        }
    }
```

Using the s`SignerWsOrRpc` wrapper to send the transaction

```rust
                    match signer_provider
                        .send_transaction(
                            TransactionRequest::default()
                                .with_from(signer_address)
                                .with_to(address.into())
                                .with_value(U256::from(1)),
                        )
                        .await
```

**Comment by prestwich** [comment]
> Additionally after manually populating the missing information I would receive this error
> 
> ```
>  Some(
>             RawValue(
>                 "invalid type: integer `10`, expected a (both 0x-prefixed or not) hex string or byte array containing between (0; 8] bytes at line 1 column 2",
>             ),
>         ),
> ```

to unblock you, this error occurs because you manually filled the json number `10` instead of the ethereum rpc specified quantity-encoded json string `"0xa"`, try manually filling with the string

**Comment by prestwich** [comment]
```
                let tx = tx.with_chain_id(rpc.get_chain_id().await?).build(&EthereumSigner::from(wallet.clone())).await.with_context(|| "failed to build tx")?;
                Ok(*rpc.send_transaction(tx.into()).await.with_context(|| "failed to send tx")?.tx_hash())
```

This appears to be misuse of the API

the first line's `build` invocation attempts to build and sign the transaction request without invoking any fillers. 

The second line would then strip that signature via the `into()` call , and invoke all relevant fillers during `send_transaction` execution before dispatching to the RPC. 

However, the second line never executes, because the `.build` call errors with the `MissingKey` error above and shortcuts execution via the `?` operator

**Comment by bonedaddy** [comment]
> to unblock you, this error occurs because you manually filled the json number 10 instead of the ethereum rpc specified quantity-encoded json string "0xa", try manually filling with the string and we'll investigate the rest

I don't think this is the case, as I never explicitly set the value 10, for example supplying the following `TransactionRequest` directly to `send_transaction` results in the json parse error, and I'm using the `TransactionRequest` builder api only, so I think the issue is internally within `alloy`.

```rust
TransactionRequest::default()
                                .with_from(signer_address)
                                .with_to(address.into())
                                .with_value(U256::from(100))                                
```

Using `TransactionRequest` as I have defined above along with revision `bfd0fda` works, so there is something that changed internally with txn serialization.

> This appears to be misuse of the API

That makes sense, ty for the explanation.

**Comment by prestwich** [comment]
> I don't think this is the case, as I never explicitly set the value 10, for example supplying the following TransactionRequest directly to send_transaction results in the json parse error, and I'm using the TransactionRequest builder api only, so I think the issue is internally within alloy.
> 
> TransactionRequest::default()
>                                 .with_from(signer_address)
>                                 .with_to(address.into())
>                                 .with_value(U256::from(100))                                
> Using TransactionRequest as I have defined above along with revision bfd0fda works, so there is something that changed internally with txn serialization.

hmmmm. this would most likely have been introduced in the type audit cc @yash-atreya Are we missing any serde decorators? 🤔

**Comment by yash-atreya** [comment]
> bfd0fda

Sorry for the delay. Missed the notifications. 

I'm unable to reproduce this on the latest commit. @bonedaddy

**Comment by yash-atreya** [comment]
> > [bfd0fda](https://github.com/alloy-rs/alloy/commit/bfd0fda492e560c3463d521958793c81bbeadfc1)
> 
> Sorry for the delay. Missed the notifications.
> 
> I'm unable to reproduce this on the latest commit. @bonedaddy

**Comment by Evalir** [comment]
I think at this point this issue is stale—@bonedaddy do you still experience this behavior? Else, we should close.
