### ISSUE TITLE
Should these derive the rlp encodable macro?

### ISSUE THREAD

**Issue by 0xJepsen** [alloy-rs/alloy#57]
https://github.com/alloy-rs/alloy/blob/b7a9c18c68a8f6736d2dbfa5621d70b34d883c46/crates/rpc-types/src/eth/transaction/typed.rs#L18

if not how should i serialize my transaction to be be signed. Working on something like thi

```rust
       let mut payload = Self::path_to_bytes(&self.derivation);

        // need to figure out how to encode the alloy TypedTransactionRequest into a Vec<u8>
        payload.extend_from_slice(tx.encode().as_slice());

        let mut signature = self.sign_payload(Instruction::Sign, &payload).await?;
```

**Comment by prestwich** [comment]
right now this crate has RPC type, which is actually a superset of the Transaction type that gets RLP encoded. we're still planning how to make this distinction smooth. related conversation in #50

**Comment by prestwich** [comment]
closing this as the answer is now clearly `no`. this is superseded by #83 and #78
