### ISSUE TITLE
[Bug] CallBuilder does not expose methods to set the sidecar of a tx

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#571]
### Component

contract

### Operating System

None

### Describe the bug

Callbuilder doesn't seem to allow the user to set the sidecar on the underlying request. This makes it unusable for e.g. rollup tx submission

**Comment by prestwich** [comment]
workaround:
- use `.map` to get mutable access to the underlying request

**Comment by EmperorOrokuSaki** [comment]
I'll take this.

**Comment by EmperorOrokuSaki** [comment]
We can close this
