### ISSUE TITLE
[Refactor]: use "signer" for single credentials and "wallet" for credential stores

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#575]
Current naming of signer types is somewhat confusing. Move to standardize naming by reviewing usage of the words "signer" and "wallet".

A signer is a single credential capable of signing hashes or txns or other data under a single address

A wallet is a credential store capable of storing multiple signers, and selecting a signer to use to sign hashes, or txns, or other data

              I want to rename `NetworkSigner` to `NetworkWallet`, and `LocalWallet` to `LocalSigner`, and always use `Wallet` to mean "a collection of credentials" and signer to mean "a single credential". but that is a more extensive refactor

_Originally posted by @prestwich in https://github.com/alloy-rs/alloy/pull/569#discussion_r1570940200_

**Comment by EmperorOrokuSaki** [comment]
I will give this a try

**Comment by prestwich** [comment]
Cool. To be clear, this is just renaming existing types/functions/etc, should be no behavior changes
