### ISSUE TITLE
[Bug] `Provider::on_builtin` connected to an `AnvilInstance` errors

### ISSUE THREAD

**Issue by alexfertel** [alloy-rs/alloy#577]
### Component

contract, provider, pubsub

### What version of Alloy are you on?

```toml
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "188c4f8", features = [
  "node-bindings",
  "contract",
  "signers",
  "providers",
] }
```

### Operating System

macOS (Apple Silicon)

### Describe the bug

The following small example errors with `unknown field input`.

```rust
use std::io::Error;
use alloy::{node_bindings::Anvil, primitives::Address, providers::ProviderBuilder, sol};

sol! {
    #[sol(rpc)]
    contract Test {
        uint8 value;

        function getter() external returns (uint8);
    }
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let anvil = Anvil::default().spawn();
    let rpc_url = anvil.endpoint();
    let provider = ProviderBuilder::new().on_builtin(&rpc_url).await.unwrap();
    let contract = Test::new(Address::ZERO, &provider);
    let Test::getterReturn { _0 } = contract.getter().call().await.unwrap();

    Ok(())
}
```

The full error is:

```
thread 'main' panicked at src/main.rs:22:68:
called `Result::unwrap()` on an `Err` value: TransportError(ErrorResp(ErrorPayload { code: -32602, message: "unknown field `input`, expected one of `from`, `to`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`, `gas`, `value`, `data`, `nonce`, `chainId`, `accessList`, `type`", data: None }))
```

**Comment by alexfertel** [comment]
This also errors:

```rust
#[tokio::main]
async fn main() -> Result<(), Error> {
    let (provider, _) = ProviderBuilder::new().on_anvil();
    let contract = Test::new(Address::ZERO, &provider);
    let Test::getterReturn { _0 } = contract.getter().call().await.unwrap();
    println!("{}", _0);

    Ok(())
}
```

With this:

```
thread 'main' panicked at src/main.rs:22:68:
called `Result::unwrap()` on an `Err` value: TransportError(Transport(Custom(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(63352), path: "/", query: None, fragment: None }, source: Error { kind: Connect, source: Some(ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) } })))
```

Which I'm assuming is because `let (provider, _) = ProviderBuilder::new().on_anvil();` drops the anvil instance. Is there any way to improve the error here? Or maybe we can leverage `#[must_use]` somehow?

**Comment by prestwich** [comment]
> unknown field `input`

how old is your anvil? i think `input` is a relatively new field

> Which I'm assuming is because let (provider, _) = ProviderBuilder::new().on_anvil(); drops the anvil instance

this is correct. we can't use `must_use` here as the binding to `_` is treated as an explicit drop, ie you ARE using it so `must_use` will have no feedback. You can name the binding `_anvil` to avoid dropping it there

**Comment by prestwich** [comment]
some followup work:
https://github.com/alloy-rs/alloy/issues/578

**Comment by prestwich** [comment]
more info
https://github.com/ethereum/go-ethereum/issues/28608
https://github.com/foundry-rs/foundry/pull/5918

**Comment by prestwich** [comment]
if you want to go ahead and run `foundryup` i believe it should install a recent anvil and fix the problem 🙌

**Comment by alexfertel** [comment]
> how old is your anvil? i think input is a relatively new field

Ah, that's it, I had a version from a few months ago. Thanks!

> we can't use must_use here as the binding to _ is treated as an explicit drop, ie you ARE using it so must_use will have no feedback. You can name the binding _anvil to avoid dropping it there

Gotcha, makes sense 👍

**Comment by alexfertel** [comment]
This looks like a good solution https://github.com/alloy-rs/alloy/issues/578
