### ISSUE TITLE
[Bug] debug_trace_call and debug_trace_call_many invalid parameter

### ISSUE THREAD

**Issue by koinov** [alloy-rs/alloy#579]
### Component

provider, pubsub

### What version of Alloy are you on?

https://github.com/alloy-rs/alloy?rev=188c4f8#188c4f8f

### Operating System

None

### Describe the bug

In alloy-provider crate I believe debug_trace_call and debug_trace_call_many functions should have  GethDebugTracingCallOptions instead of  GethDebugTracingOptions

https://github.com/alloy-rs/alloy/blob/6ce3c05062fe77a449d761984ec89d47e7d0253e/crates/provider/src/debug.rs#L74
https://github.com/alloy-rs/alloy/blob/6ce3c05062fe77a449d761984ec89d47e7d0253e/crates/provider/src/debug.rs#L88

Thank you for your attention.

**Comment by mattsse** [comment]
yeah these should indeed be `GethDebugTracingCallOptions`
