### ISSUE TITLE
[Feature] Add more builder style functions for large rpc args

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#583]
### Component

rpc

### Describe the feature you would like

we're lacking convenience functions to configure large rpc args such as:

https://github.com/alloy-rs/alloy/blob/2e16c84df9040ffec8dcea809e5b1706e131d63a/crates/rpc-types-trace/src/geth/mod.rs#L486-L498

https://github.com/alloy-rs/alloy/blob/2e16c84df9040ffec8dcea809e5b1706e131d63a/crates/rpc-types-trace/src/filter.rs#L11-L11

## TODO

* add helper functions in builder style (`fn x(self, arg) -> Self`) that make it easier to set certain options

**Comment by EmperorOrokuSaki** [comment]
I will take this.
