### ISSUE TITLE
[Feature] NonceFiller fills nonce without specified spender - FromFiller?

### ISSUE THREAD

**Issue by halo3mic** [alloy-rs/alloy#588]
### Component

provider, pubsub

### Describe the feature you would like

I believe it would be great to have a very simple nonce filler that doesn't require specifying the sender or needing two providers (I'm not sure if I understand the latter suggestions from below). 
https://github.com/alloy-rs/alloy/blob/c7a51e9b20e8d136572c30fc889799d97f50bd02/crates/provider/src/fillers/nonce.rs#L22-L26

If I understand correctly, the issue with using SignerFiller for this is that the nonce needs to be filled before SignerFiller is executed and nonce would need to execute SignerFiller before to get the signer address. 

I was wondering if this could be solved with additional filler `FromFiller` that would be added whenever SignerFiller is added: 
```rust
    pub fn signer<S>(self, signer: S) -> ProviderBuilder<L, JoinFill<JoinFill<F, FromFiller>, SignerFiller<S>>, N>
        where S: NetworkSigner<N>, N: Network
    {
        self.filler(FromFiller::new(signer.default_signer()))
            .filler(SignerFiller::new(signer))
    }
``` 

Here are the changes: https://github.com/alloy-rs/alloy/compare/main...halo3mic:alloy:from_filler

(This functionality would not work if SignerFiller was added manually with `filler` method and not through `signer` method)

**Comment by gakonst** [comment]
Believe the SignerFiller covers this now, no? https://github.com/alloy-rs/alloy/commit/3faa1fc10949602ccba946686167ef66774a27f1

**Comment by gakonst** [comment]
Believe the SignerFiller covers this now, no? https://github.com/alloy-rs/alloy/commit/3faa1fc10949602ccba946686167ef66774a27f1

**Comment by halo3mic** [comment]
> Believe the SignerFiller covers this now, no? [3faa1fc](https://github.com/alloy-rs/alloy/commit/3faa1fc10949602ccba946686167ef66774a27f1)

Yea, wasn't on the latest changes

Thanks!
