### ISSUE TITLE
[Bug] Event subscription filter not filtering.

### ISSUE THREAD

**Issue by developeruche** [alloy-rs/alloy#597]
### Component

provider, pubsub

### What version of Alloy are you on?

188c4f8

### Operating System

macOS (Apple Silicon)

### Describe the bug

When subscribing to event, `Filter` doesn't work as it ought to. 

For more context, here is the code performing the subscribed log; 
https://github.com/developeruche/alloy-examples/blob/main/examples/subscriptions/examples/subscribe_to_log_external_provider.rs

these are some logs gotten during the subscription;
https://gist.github.com/developeruche/e86e35724ae5c6db1f5c13ad78268be9

one of the logs gotten came from this tx;
https://etherscan.io/tx/0x47495262a6ba8ea4e3fd2fd9031ac80eb2b08354ab8173e9edb10a5c63d08bdb

 this has completely nothing to do with the filter I provided to the subscription function.

**Comment by prestwich** [comment]
duplicate of #595

**Comment by willmalcs** [comment]
not duplicate of #595 as the issue there was only the filters generated by the sol! macro. manually making filters worked fine for me.

looks like for this it's prob just the particular rpc url used in the example going wrong, the following all work fine:

```rust
let rpc_url = "wss://ethereum-rpc.publicnode.com";
let rpc_url = "wss://mainnet.gateway.tenderly.co";
let rpc_url = "wss://eth.drpc.org";
```

**Comment by developeruche** [comment]
> not duplicate of #595 as the issue there was only the filters generated by the sol! macro. manually making filters worked fine for me.
> 
> looks like for this it's prob just the particular rpc url used in the example going wrong, the following all work fine:
> 
> ```rust
> let rpc_url = "wss://ethereum-rpc.publicnode.com";
> let rpc_url = "wss://mainnet.gateway.tenderly.co";
> let rpc_url = "wss://eth.drpc.org";
> ```

Yeah... I switched to Alchemy and it filters fine

**Comment by prestwich** [comment]
can this then be closed as a "someone else's problem" issue? :)

**Comment by developeruche** [comment]
Sure sure

**Comment by developeruche** [comment]
someone else's problem
