### ISSUE TITLE
[Feature] Add `JSON Web Token` (`JWT`) token generation and validation support 

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/alloy#599]
### Component

transports

### Describe the feature you would like

To add `JWT` claims generation and validation support 

Besides having use in Foundry it is a common method of authentication between execution client / consensus client

For reference:

- https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/rpc/transports/common.rs
- https://crates.io/crates/tower-jwt

Both implementations use: https://github.com/Keats/jsonwebtoken

### Additional context

It is possibly preferred that this is added to a separate new repo in the `alloy` org

@mattsse indicated that this is also useful for Reth

I should be able to implement it and propose a PR if that is desired

**Comment by mattsse** [comment]
we should probably put this in the engine types crate

don't think it's worth it to add a new crate for this

**Comment by prestwich** [comment]
> we should probably put this in the engine types crate

makes sense to me
