### ISSUE TITLE
[Feature] Set default poll interval based on connected chain

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#604]
### Component

network, json-rpc, provider, pubsub

### Describe the feature you would like

ref 

https://github.com/alloy-rs/alloy/pull/437#discussion_r1575965143

if not local

**Comment by DaniPopes** [comment]
Related https://github.com/alloy-rs/alloy/pull/437#discussion_r1576824310
> i'd make this 2s given the rise of L2s with faster blocktimes
