### ISSUE TITLE
[Feature] Change way we specify the `BlockId` in some methods of the provider

### ISSUE THREAD

**Issue by NicolasWent** [alloy-rs/alloy#613]
### Component

provider, pubsub

### Describe the feature you would like

In the following functions of the provider:

- [get_transaction_count](
https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L627)
- [get_balance](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L711)
- [get_storage_at](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L748)
- [get_code_at](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L758)
- [call](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L852)
- [call_with_overrides](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L862)
- [estimate_gas](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L884)
- [get_proof](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L935)
- [create_access_list](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L947)
- [trace_call](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L960)
- [trace_call_many](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L977)

I think it would more user friendly if we could change the way we specify the `BlockId` field.

For example for `get_transaction_count` in the latest block, we currently need to do:
```rust
provider.get_transaction_count(address, BlockId::latest()).await?;
```

Instead I think it would more user friendly to do it this way (completely remove the `BlockId` parameter):
```rust
provider.get_transaction_count(address).await?;
```

And if someone wants to get the transaction count at a specific block:
```rust
provider.get_transaction_count(address).block(BlockId::number(42)).await?;
```

### Change motivation

Most of the methods I specified above, especially:
- [get_transaction_count](
https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L627)
- [get_balance](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L711)
- [get_code_at](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L758)
- [estimate_gas](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L884)
- [create_access_list](https://github.com/alloy-rs/alloy/blob/cad7935d69f433e45d190902e58b1c996b35adfa/crates/provider/src/provider.rs#L947)

Are, in the vast majority of time, used only on the latest block. And it is not that user friendly to specify the BlockId every time for the the following reasons:
- We need to add an import to `BlockId` in every file that we make the call when we actually don't need the specific block
- When we are in a workspace with multiple crates, we also need to go back to `Cargo.toml` and add the `alloy-rpc-types` crate specially for this.

With the proposed change it will be more user friendly for most use cases which use latest block and still remain user friendly for users that have some specific archive needs.

### Additional context

Before hand, we had only to write `None` when we didn't needed a specific block, but it was changed after #514 in #516 for consistency reasons

This is a highly breaking change.

**Comment by NicolasWent** [comment]
> This comment from the PR may address this issue: [#516 (comment)](https://github.com/alloy-rs/alloy/pull/516#issuecomment-2056331152) @prestwich

In this comment my suggestion most looks like:
> or to switch to a rpc builder pattern for return values of those types. which seems bad

But I don't know the specific reasons or why it would be bad to use an rpc builder pattern?

**Comment by NicolasWent** [comment]
Why would we need:
> basically it's significantly less simple all around. agree that doing call().with_overrides().block().await? feels decent

Could we just do:
```rust
call().block().await?
```

Another objection that I thought about is for people that implements some Mock providers for their tests. I think it might get quite complicated to Mock a Provider if we have custom IntoFuture

**Comment by prestwich** [comment]
```
call().block().await?
```

well, to make this work right we'd have to implement like so:

```
trait Provider<T, N> {
   fn call(address: Address, data: Bytes) -> CallBuilder<Self, T, N>
}

struct CallBuilder<P, T, N> {
    address: Address,
    data: Bytes,
    block: Option<BlockId>,
    overrides: Overrides,
    provider: ProviderRef<P,T,N>,
}

impl<P,T,N> CallBuilder<P,T,N> {
    fn state_overrides(mut self, overrides: Overrides) -> Self
    fn block(mut self, block: BlockId)
}

impl<P,T,N> IntoFuture for CallBuilder<P,T,N> { 
    type IntoFuture = RpcCall<...>;
}
```

**Comment by NicolasWent** [comment]
> well, to make this work right we'd have to implement like so:

It seems that with this approach, we are loosing the "trait" part of the provider. Which makes it hard for people to implement a new provider right?

Maybe another approach would be to have 2 Provider types:
- One high level provider that creates the `CallBuilder` and all other builders
- One low level provider that takes all possible arguments directly.

Once the `CallBuilder` is awaited, it calls the lower level provider.
This way if someone wants to change the behavior, like creating a new provider that uses a cache or a mock provider, he can just override the lower level provider.

But I agree that this approach also seems to complicate things a lot

Just putting back the `Option<BlockId>` for the methods that don't require specific blocks might be simpler overall.
