### ISSUE TITLE
[Feature] Change poll_interval from u64 to Duration

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#618]
### Component

provider, pubsub

### Describe the feature you would like

this is mainly useful as duration:

https://github.com/alloy-rs/alloy/blob/main/crates/rpc-client/src/client.rs#L182-L183

returning this as duration makes it harder to mess up the u64 -> Duration::from_millis call

**Comment by DaniPopes** [comment]
Same for set

**Comment by EmperorOrokuSaki** [comment]
I will take this.

**Comment by prestwich** [comment]
exact scope is to change the return-type for the function, NOT to change the struct prop type
