### ISSUE TITLE
Consider higher default channel sizes

### ISSUE THREAD

**Issue by yash-atreya** [alloy-rs/alloy#622]
### Component

provider, pubsub

### Operating System

None

### Describe the bug

Currently the `channel_size` in the `PollerBuilder` defaults to 16. Due to this the `recv` channel will almost always lag behind and drop messages sent by the sender if the number of messages > 16 and the `recv` channel is unable to process the messages fast enough to keep the buffer <= 16.

**Comment by prestwich** [comment]
not a bug, intended behavior. The alternative is unlimited memory growth in an mpsc::UnboundedReceiver, which would also prevent us from cheaply cloning

there's a conversation to be had about a higher default, but I'm not particularly in favor of it
