### ISSUE TITLE
[Bug] Invalid encoding for pre-eip658 tx receipts

### ISSUE THREAD

**Issue by petscheit** [alloy-rs/alloy#630]
### Component

consensus, eips, genesis

### Operating System

None

### Describe the bug

In `alloy_consensus`, the `Receipt` struct contains the status parameter as a boolean. This is a problem when encoding pre-eip658 (added with Byzantium) receipts, as this parameter was introduced with this hardfork. In `alloy-rpc-types` the `TransactionReceipt` implements this correctly, wrapping the status as an `Option<>`.

**Comment by prestwich** [comment]
It's significantly more complicated than this, as pre-658 the consensus receipt contained the post-execution state root. The status is _not_ optional in consensus receipts. But we are failing to capture the fact that pre-658 that field contained a hash instead of a bool cc @mattsse
