### ISSUE TITLE
[Feature] Move block hash types to alloy-eips

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#633]
### Component

consensus, eips, genesis, rpc

### Describe the feature you would like

https://github.com/alloy-rs/alloy/blob/4d77029ba61284a6b4185f46581b4d9bce34f5fd/crates/rpc-types/src/eth/block.rs#L483-L483

and 

https://github.com/alloy-rs/alloy/blob/4d77029ba61284a6b4185f46581b4d9bce34f5fd/crates/rpc-types/src/eth/block.rs#L429-L429

are commonly used types. Currently they reside in rpc-types, importing the entire rpc-types crate just for these types is very inconvenient.

we already moved the EIP-1898 related types to alloy-eips, 
It would make more sense to move those types there as well and then re-export from rpc-types just as BlockId

https://github.com/alloy-rs/alloy/blob/4d77029ba61284a6b4185f46581b4d9bce34f5fd/crates/rpc-types/src/eth/block.rs#L6-L8

**Comment by lakshya-sky** [comment]
can I take this one?

**Comment by prestwich** [comment]
sure, just assigned to you :)

**Comment by mattsse** [comment]
@lakshya-sky bonus points for impl DIsplay for blockNumHash as well
