### ISSUE TITLE
[Feature] ERC-6492 support

### ISSUE THREAD

**Issue by chris13524** [alloy-rs/alloy#643]
### Component

rpc

### Describe the feature you would like

Support to verify signatures using EIP-6492 (supporting both contract wallets & EOAs) similar to [how Viem supports it](https://viem.sh/docs/actions/public/verifyMessage#verifymessage). Example of Rust implementation [here](https://github.com/WalletConnect/WalletConnectRust/blob/main/relay_rpc/src/auth/cacao/signature/eip6492.rs).

This would be an easy way for Rust applications to verify that wallet signatures are correct.

**Comment by prestwich** [comment]
Almost all ERCs are out of scope for alloy's main repos (main exception being ERC-712). We love when people build extension traits in other crates, and would likely be willing to link to it in docs or elsewhere. If you decide to build and publish, please don't use the `alloy- *` namespace on crates.io :)

**Comment by chris13524** [comment]
Thanks! I figured this was out-of-scope as I didn't even see EOA signature validation here. Will certainly consider publishing (not using `alloy-*`), and would be great to have an ecosystem around alloy as new crates pop up. Loving the library so far!

**Comment by prestwich** [comment]
> EOA signature validation

this is actually a docs generation bug. There are several recovery methods on the signature type

```
Signature::recover_address_from_msg
Signature::recover_address_from_prehash
```

Then there's also [`Signed::<T>::recover_signer`](https://github.com/alloy-rs/alloy/blob/main/crates/consensus/src/signed.rs#L57C12-L57C26)
