### ISSUE TITLE
[Feature] Add engine api extension

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#658]
### Component

provider, pubsub, rpc

### Describe the feature you would like

mostly for testing purposes, it would be nice to have an `EngineApiExt` trait similar to 

https://github.com/alloy-rs/alloy/blob/c058e32d2025a2fd60b2617554ade7afeaca9c47/crates/provider/src/ext/admin.rs#L11

see also:

https://github.com/paradigmxyz/reth/blob/0938504f4a265eec74e0b833ab5c41d66649bdee/crates/rpc/rpc-api/src/engine.rs#L27-L27

## TODO 
* add extension trait for engine API
* can use ethereum engine types, but I think eventually we'd need a helper trait because some request params are also network specific
* should be feature gated because not useful for regular usage

**Comment by leruaa** [comment]
I can take this on.

**Comment by leruaa** [comment]
@mattsse May I continue on that by replacing the trait in Reth https://github.com/paradigmxyz/reth/blob/0938504f4a265eec74e0b833ab5c41d66649bdee/crates/rpc/rpc-api/src/engine.rs#L27-L27 by the new trait from Alloy?

Assuming Alloy rev in Reth will need to be bumped obviously ;)

**Comment by mattsse** [comment]
we still need this because this also generates the server code
