### ISSUE TITLE
[Bug] cannot derive Clone with sol macro from an ABI

### ISSUE THREAD

**Issue by erikreppel** [alloy-rs/alloy#659]
### Component

contract

### What version of Alloy are you on?

alloy v0.1.0 (https://github.com/alloy-rs/alloy?rev=bbef8de#bbef8de3)

### Operating System

macOS (Apple Silicon)

### Describe the bug

(from discussion in telegram channel)
The sol macro using an abi file. The sol macro seems to automatically add #[derive(Clone)] to SolStructs and errors, but not to SolEvents, so trying to derive Clone when using an abi as input breaks because of conflicting implementations of Clone on SolStructs and errors.

![telegram-cloud-document-1-5012973626165560801](https://github.com/alloy-rs/alloy/assets/7102968/c9d25050-2b33-4dac-9a8a-71d32e532b56)
![telegram-cloud-document-1-5012973626165560803](https://github.com/alloy-rs/alloy/assets/7102968/66180cb7-9527-4ffa-81eb-0f69df13be68)

![telegram-cloud-document-1-5012973626165560806](https://github.com/alloy-rs/alloy/assets/7102968/d9adbeaa-2bec-4b92-bd38-f60b52bcc510)

![telegram-cloud-document-1-5012973626165560806](https://github.com/alloy-rs/alloy/assets/7102968/6acc4c77-e617-4fb2-8e60-db04fad1f3f8)

**Comment by prestwich** [comment]
quickest resolution would be to add a clone derive to the solevent

**Comment by prestwich** [comment]
As follow up, we should probably make sure that we're completely consistent across all generated types
