### ISSUE TITLE
[Bug] Full BlockTransactions doesn't offer access to Transaction slice

### ISSUE THREAD

**Issue by sfyll** [alloy-rs/alloy#665]
### Component

rpc

### Operating System

None

### Describe the bug

Hello sirs.

Wonderful job!

Filling the above. Basically, it's impossible to access the _Full_ transaction field from the BlockTransactionHashesInner object as the only exposed API will collapse a _Full_ transaction into its transaction hash. I would classify this as a bug and not a feature request as it is quite misleading, but happy to be corrected, mostly nomenclature to be honest. It does seem erroneous to download full payloads only to be offered access to the transaction hashes, which are returned in default mode anyways.

Obviously, something might have escaped me from the API, which might deprecate this bug report. Happy to stand corrected!

**Comment by prestwich** [comment]
maybe i am missing something, but `if let BlockTransactions::Full(txns) = block_txns { ... }` should unblock you. 

regardless, it's straightforward to add an `as_full(&self) -> Option<&[T]>` so i'll do that

**Comment by prestwich** [comment]
okay it turns out that all the impls here are only for `T = Transaction` so i may need a trait abstraction for `Transaction` if i want to make it reusable across networks 🤔

**Comment by prestwich** [comment]
issue #666 🤘 will add a convenience function to convert to `Option<&[T]>` and a convenience iterator over &T

**Comment by sfyll** [comment]
damn that is very fast ! next one is on me then 🫡
