### ISSUE TITLE
[Feature] Constrain `N::TransactionResponse` type to allow access to the hash or other tx details

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#667]
necessary followup work: 
              - decide how to bound the `N::TransactionResponse` type to allow access to the hash

_Originally posted by @prestwich in https://github.com/alloy-rs/alloy/issues/666#issuecomment-2090574461_

**Comment by gakonst** [comment]
```
trait TransactionResponse {
    fn hash(&self) -> B256
}
```

similar to Receipt, needs to be implemented for AnyNetwork / EthereumNetwork

https://github.com/alloy-rs/alloy/blob/main/crates/network/src/any/mod.rs#L74
https://github.com/alloy-rs/alloy/blob/main/crates/network/src/ethereum/mod.rs#L34

**Comment by yash-atreya** [comment]
Closed by #835
