### ISSUE TITLE
Remove catch-all on `TransactionReceipt` and `Block` and use `Rich`

### ISSUE THREAD

**Issue by Evalir** [alloy-rs/alloy#67]
### Component

rpc-types

### Operating System

None

### Describe the bug

https://github.com/alloy-rs/alloy/pull/66 was expedited to unblock the providers migration on foundry. However, this introduces a catch-all that we'd rather not have. Once https://github.com/foundry-rs/foundry/pull/6219 is merged we should remove this catch-all field and instead use a wrapper type `WithExtraFields<T>` that can hold arbitrary values on the map, and the original type too.

**Comment by prestwich** [comment]
closing as complete considering the any network now exists
