### ISSUE TITLE
[Feature] Implement Arbitrary for BlobTransactionSidecar properly

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#680]
### Component

consensus, eips, genesis

### Describe the feature you would like

https://github.com/alloy-rs/alloy/blob/d78e79e9b328a826d924e9732589dcc3bef64f38/crates/eips/src/eip4844/sidecar.rs#L18-L18

Arbitrary impl should produce:
* random blobs + matching commitments + proofs

**Comment by prestwich** [comment]
It would be easy to use the `SidecarBuilder` to achieve this :)

**Comment by leruaa** [comment]
I can take this on.

**Comment by leruaa** [comment]
@prestwich Unfortunately using `SidecarBuilder` is not possible because it's in `alloy-consensus` whike `BlobTransactionSidecar` is in `alloy-eips`, and adding a dep of `alloy-consensus` in `alloy-eips` creates a circular dep. 

Do you think ir makes sense to move `SidecarBuilder` to `alloy-eips`?

**Comment by prestwich** [comment]
yes i think that would make sense
