### ISSUE TITLE
[Bug] Websocket reconnection does not work

### ISSUE THREAD

**Issue by stpnov** [alloy-rs/alloy#690]
### Component

provider, pubsub

### Operating System

None

### Describe the bug

If the connection to the websocket is lost, the connection will not be re-established.
I thought the problem with reconnecting to the websocket in alloy was fixed, but the bug has been moved from ethers.
https://github.com/gakonst/ethers-rs/issues/2323

**Comment by prestwich** [comment]
Can you provide additional information? Are you mirroring this issue from the ethers repo, or encountering a new alloy issue?

**Comment by prestwich** [comment]
can you say what the bug is or its observed effects?

**Comment by prestwich** [comment]
are you sure your link is correct? could you link to a commit hash instead of a branch next time please?

**Comment by triamazikamno** [comment]
This would be the correct commit hash link:
https://github.com/alloy-rs/alloy/blob/6c58a0a2f1b2325aeba6a359e5ea5f4faa08bda0/crates/pubsub/src/service.rs#L205

**Comment by prestwich** [comment]
ah, if reconnection has an error, you think the default behavior should be to keep attempting it repeatedly?

**Comment by prestwich** [comment]
you can customize the behavior by writing implementing [`PubSubConnect`](https://alloy-rs.github.io/alloy/alloy_pubsub/connect/trait.PubSubConnect.html) for some type

**Comment by prestwich** [comment]
given that the behavior is intended and there's an official route to changing that behavior, I'm going to close the issue as not planned

**Comment by the-emerald** [comment]
For anyone who stumbles upon this and wants a retrying webscoket connector, here is an example that uses exponential backoff (using the crate `backoff`):

```rs
use alloy::{
    providers::{Provider, ProviderBuilder},
    pubsub::{ConnectionHandle, PubSubConnect},
    rpc::client::ClientBuilder,
    transports::{impl_future, ws::WsConnect, TransportResult},
};
use anyhow::Result;
use backoff::ExponentialBackoff;

#[tokio::main]
async fn main() -> Result<()> {
    let ws = WsConnect::new("wss://eth-mainnet.g.alchemy.com/v2/redacted");
    let ws = RetryWsConnect(ws);

    let client = ClientBuilder::default().pubsub(ws).await?;

    let provider = ProviderBuilder::new()
        .with_recommended_fillers()
        .on_client(client);

    println!("{}", provider.get_block_number().await?);

    Ok(())
}

/// Retrying websocket connection using exponential backoff
#[derive(Clone, Debug)]
pub struct RetryWsConnect(WsConnect);

impl PubSubConnect for RetryWsConnect {
    fn is_local(&self) -> bool {
        self.0.is_local()
    }

    fn connect(&self) -> impl_future!(<Output = TransportResult<ConnectionHandle>>) {
        self.0.connect()
    }

    async fn try_reconnect(&self) -> TransportResult<ConnectionHandle> {
        backoff::future::retry(ExponentialBackoff::default(), || async {
            Ok(self.0.try_reconnect().await?)
        })
        .await
    }
}
```
