### ISSUE TITLE
[Feature] Consider changing the return type of `SidecarCoder::decode_all()`

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [alloy-rs/alloy#691]
### Component

consensus, eips, genesis

### Describe the feature you would like

Currently, for some unknown reason, we have `Option<Vec<Vec<u8>>>>`, but we could change it to `Option<Vec<u8>>`. This will improve performance and we won't have to do `.concat()` on the result. When we encode the data, a slice is needed, but when we decode the data, we get a vector of vectors.
https://github.com/alloy-rs/alloy/blob/20b815293d3ba34969fb5eed7b983344c61571e6/crates/consensus/src/transaction/eip4844/builder.rs#L152-L153

**Comment by prestwich** [comment]
This is intentional. The coder codes each slice individually. `decode_all` decodes all slices that were coded
