### ISSUE TITLE
[Bug] Make the `alloy` library independent of `wasm-bindgen`

### ISSUE THREAD

**Issue by MathieuDutSik** [alloy-rs/alloy#700]
### Component

provider, pubsub, transports

### What version of Alloy are you on?

0bb7604f186a78cdee911fa7fbc0ca36465a6902

### Operating System

macOS (Intel)

### Describe the bug

The code of `alloy` has a dependency on `wasm-bindgen`. It can be seen by doing:
```cargo tree --target wasm32-unknown-unknown```

The error can be triggered by having the following `Cargo.toml`:
```
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "0bb7604f186a78cdee911fa7fbc0ca36465a6902", default-features = false, features = [ "providers" ] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.14", features = ["js"] }
```

with the rust `main.rs` program
```
use alloy::providers::Provider;

fn main() {
    println!("Hello world");
}
```

Then we have the error
```➜  debug git:(main) ✗ wasmer test.wasm
error: Unable to instantiate the WebAssembly module
╰─▶ 1: Error while importing "__wbindgen_placeholder__"."__wbindgen_describe": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
```

That error is because using `wasm-bindgen` implies the use inside a browser. That is not the context in which we are using alloy. We want to use our own `Provider`.

**Comment by DaniPopes** [comment]
We rely internally on spawning tasks

https://github.com/alloy-rs/alloy/blob/42594c2dfadd07a38139f4a70935c538a9305023/crates/transport/Cargo.toml#L26-L27

cc @prestwich can we even support this?

**Comment by prestwich** [comment]
we could disable pubsub and pendingtxns i guess?

**Comment by MathieuDutSik** [comment]
In our use case, we only need support for `eth_getLogs` and `eth_call`. So, that would be fine for us.

**Comment by DaniPopes** [comment]
In that case we can put the `Spawnable` trait behind a feature gate on wasm and panic if the feature is not enabled
https://github.com/alloy-rs/alloy/blob/c65fd8ac4eb5e595f3c2ba304af327d37fcb1f3c/crates/transport/src/utils.rs#L51-L59

**Comment by MathieuDutSik** [comment]
That would be great.

**Comment by prestwich** [comment]
So quick recap:
- put wasm-bindgen-futures behind a feature flag
- if feature not enabled, panic on Spawnable::spawn invocation
- users MAY NOT enable pubsub and MAY NOT use alloy-provider
- users SHOULD use alloy-rpc-client and make requests directly
