### ISSUE TITLE
All Provider calls fail

### ISSUE THREAD

**Issue by th3outcast** [alloy-rs/alloy#734]
## Issue
All provider calls within my project fail. Even down to the simplest calls like getting the latest block number.

`Note`: this is not the fault of my RPC providers, as it also fails with **Alchemy** - which has been running the same code fine using **ethers-rs**, and is still running fine when using it with **foundry** - but now I'm porting it to **alloy** and ran into this issue.

Can I get any pointers?

## Version
Commit hash - [6c58a0a]

## Code
```rust
    #[tokio::test]
    async fn test_get_lbn() -> Result<()> {
        // Set up the HTTP transport which is consumed by the RPC client.
        let rpc_url = "https://eth.merkle.io".parse()?;

        // Create a provider with the HTTP transport using the `reqwest` crate.
        let provider = ProviderBuilder::new().on_http(rpc_url);

        // Get latest block number.
        let latest_block = provider.get_block_number().await?;

        println!("Latest block number: {latest_block}");

        Ok(())
    }
```

## Error
```bash
Error: error sending request for url (https://eth.merkle.io/)

Caused by:
   0: error sending request for url (https://eth.merkle.io/)
   1: client error (Connect)
   2: invalid URL, scheme is not http
```

## Cargo.toml
A snippet of my `Cargo.toml`

```rust
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "6c58a0a", features = [
    "contract",
    "network",
    "providers",
    "provider-ws",
    "rpc-types-eth",
    "signers",
    "signer-wallet",
] }

```

## Platform
OS: Arch Linux x86_64
Kernel: 6.8.9-arch1-2

**Comment by prestwich** [comment]
this error indicates the reqwest tls feature is not enabled (and therefore reqwest wants only http:// urls)

**Comment by prestwich** [comment]
to resolve it, add "transport-http" to your feature list

**Comment by th3outcast** [comment]
Thanks a lot, it worked!!!

I really appreciate the extremely quick response.

**Comment by prestwich** [comment]
no worries. we are still a bit short on troubleshooting docs 😅

**Comment by th3outcast** [comment]
I'll definitely be on the lookout. Keep up the brilliant work!!
