### ISSUE TITLE
[Feature] Make Provider (RpcClient) Clone

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#76]
### Component

providers

### Describe the feature you would like

currently the Provider and RpcClient are not Clone which is a limitation when we want to use a provider in a type that ideally is Cloneable, otherwise we'd need to go back to `Arc<Provider>`

all of this can be made Clone, we already assume that Transport is Clone for the Provider to work:

https://github.com/alloy-rs/alloy/blob/4ed367e1dbc4bed77794622fceb9a38131fcc9a6/crates/rpc-client/src/client.rs#L21-L28

**Comment by prestwich** [comment]
if making it clone we need to share the id between clones, otherwise pubsub providers may confuse responses

**Comment by DaniPopes** [comment]
`RpcClient` is `Clone` as now it is `Arc<RpcClientInner>`, and `RootProvider` is too.
`RpcClientInner` isn't, but I think this is enough to close this issue.
