### ISSUE TITLE
[Feature] Transaction traits

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#77]
### Component

new component

### Describe the feature you would like

Transaction traits that provide common getters/setters for transactions. Should be implemented on primitive tx types as described in #73. 
 
```
trait Transaction { value, data, etc  }
trait LegacyTransaction: Transaction { fn get/set_gas_price() }
trait TransactionEip1559: Transaction  { fn get/set_max_priority_fee_per_gas() }
trait TransactionEip2930: LegacyTransaction { fn get/set_access_list() }
```

**Comment by Evalir** [comment]
What would the base `Transaction` trait be used for?

**Comment by prestwich** [comment]
getters and setters for all fields common to all transactions including:
- data
- value
- to (including null for contract creation)
- gas limit
- nonce

goal is to support Provider implementation populating transactions in a network-agnostic manner as follows:

Something like this:
```
async fn fill_transaction<T: Transaction>(&self, tx: &mut T) -> Result<()>;
async fn fill_dyn_transaction(&self, tx: &mut dyn Transaction) -> Result<()>;
async fn fill_1559_transaction<T: Transaction1559>(&self, tx: &mut T) -> Result<()> {
    self.fill_transaction(tx).await?;
    self.fill_1559_fields(tx).await?;
}
async fn fill_dyn_1559_transaction(self, tx: &mut dyn Transaction1559) -> Result<()> {
    self.fill_dyn_transaction(self, tx).await?;
    self.fill_dyn_1559_fields(tx).await?;
}
```

**Comment by onbjerg** [comment]
should be done
