### ISSUE TITLE
[Feature] Get abi error data from an error response on call / send transaction

### ISSUE THREAD

**Issue by rplusq** [alloy-rs/alloy#787]
### Component

contract

### Describe the feature you would like

Right now, assuming I have a contract Foo with a function bar, if it has an error, I have to do a lot of parsing / handling to get the abi error. I would like to have a more convenient function to handle this.

Example of how I'm doing it right now:

```rust
sol!(
    #[allow(missing_docs)]
    #[sol(rpc)]
    Foo,
    "abis/Foo.json"
);

let foo_contract = Foo::new(FOO_ADDRESS, &provider);

let tx_receipt = match foo_contract
        .bar()
        .from(signer)
        .send()
        .await
    {
        Ok(result) => result.get_receipt().await?,
        Err(error) => match error {
            Error::TransportError(TransportError::ErrorResp(err)) => {
                let data = err.data.unwrap_or_default();
                let data = data.get().trim_matches('"');
                let data = Bytes::from_str(data)?;
                let decoded_error = Foo::FooErrors::abi_decode(&data, true)?;

            }
            _ => {
                return Err(eyre::eyre!(
                    "Received TransportError with data: {:?}",
                    eyre::eyre!(error)
                ))
            }
        },
    };
```

**Comment by prestwich** [comment]
related logic from ethers-rs [here](https://github.com/gakonst/ethers-rs/blob/51fe937f6515689b17a3a83b74a05984ad3a7f11/ethers-providers/src/rpc/transports/common.rs#L32)

we essentially need to
- check if the response is an error response
- deserialize error contents into `serde_json::Value`
- spelunk to find revert data
- attempt to decode that revert data as a `MyContract::MyContractErrors` type
- return that data as a raw revert if deserialization failed

**Comment by alexfertel** [comment]
Can I give this a shot? It's a thing that would be great to have.

**Comment by rplusq** [comment]
Starting to work on this
