### ISSUE TITLE
[Feature] make rpc-client and below wasm-friendlier 

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#792]
So quick recap:
              - put wasm-bindgen-futures behind a feature flag
              - if feature not enabled, panic on Spawnable::spawn invocation
              - users MAY NOT enable pubsub and MAY NOT use alloy-provider
              - users SHOULD use alloy-rpc-client and make requests directly

_Originally posted by @prestwich in https://github.com/alloy-rs/alloy/issues/700#issuecomment-2098481258_

**Comment by leruaa** [comment]
I can take this on.
