### ISSUE TITLE
[Bug] Confusing `BlockTransactions::Uncle` variant

### ISSUE THREAD

**Issue by Rjected** [alloy-rs/alloy#805]
### Component

rpc

### Operating System

None

### Describe the bug

Just noting something confusing I ran into - I've been using alloy for getting blocks with full txs and came across this block:
https://holesky.etherscan.io/block/1406078

which has zero transactions, so `transactions` deserializes to `BlockTransactions::Uncle`. This one is clearly not an uncle so it was kind of confusing to see it deserialized like that. Although it seems ambiguous to deserialize into any of the variants.

I was using some reth conversion code, which assumed that `Uncle` meant that full transactions were not present. Had to make this fix:
https://github.com/paradigmxyz/reth/pull/8284/commits/47935c6b35c1c886d4bdce65168ea343d913a9da#diff-577822db25be7f22809b10329e82f83cbf6887190248af08e008d28a2eebca1cR40-R46

**Comment by DoTheBestToGetTheBest** [comment]
Should we change Uncle variant to NoTransaction ?

**Comment by mattsse** [comment]
@Rjected I think the problem you run into is that [] is deserialized into Hashes? because this is the first matching variant.

the fix in reth we def need, we could also swap the order

**Comment by Rjected** [comment]
> @Rjected I think the problem you run into is that [] is deserialized into Hashes? because this is the first matching variant.
> 
> the fix in reth we def need, we could also swap the order

Yeah, we actually had uncle as the default here:
https://github.com/alloy-rs/alloy/blob/0fc11ec751ec6f7a100a576daff93f12b64573f8/crates/rpc-types/src/eth/block.rs#L25-L26
