### ISSUE TITLE
[Feature] `AnyNetwork`

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/alloy#81]
### Component

providers, rpc-types

### Describe the feature you would like

implement the network trait from #80 for an `AnyNetwork` which contains the standard ethereum JSON-RPC types + an `extra_fields: HashMap<String, Value>`. If necessary, differentiate `AnyTransaction` from the transaction types described in #73

**Comment by prestwich** [comment]
cc @onbjerg @Evalir

**Comment by leruaa** [comment]
I would like to take this on
