### ISSUE TITLE
[Refactor] Nit: align naming of  `tx_hash` / `transaction_hash`, `tx_type` / `transaction_type`

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/alloy#814]
### Component

consensus, eips, genesis, network, json-rpc, rpc

### Describe the feature you would like

A nit, but I noticed an inconsistency when switching between a pending transaction (`.tx_hash()`) and receipt (`.transaction_hash`):

For `Log` and `Receipt`: `transaction_hash` is used.
For `TxEnvelope`, `Heartbeat`, `TraceResult`: `tx_hash` is used.

Another case is `tx_type` and `transaction_type`:

For `Transaction`, `TransactionReceipt`, `TransactionRequest`: `transaction_type` is used.
For `ReceiptEnvelope` and : `tx_type` is used.

I propose we align the naming. My preference is `transaction_hash` and `transaction_type`, this is in line with `signature_hash`.

**Comment by gakonst** [comment]
It seems like the main motivator here is intellisense so if we do something we could use doc(alias) for things that make sense for autocomplete, and keep the other type names the same.
