### ISSUE TITLE
[Feature] ERC-3668 CCIP Support

### ISSUE THREAD

**Issue by lucemans** [alloy-rs/alloy#84]
### Component

json-rpc, rpc-client

### Describe the feature you would like

Implementation of eip-3668, the cross chain interoperability protocol.

CCIP is already natively integrated in most other ethereum libraries, enabled by default, and powers a core part of the ENS protocol.

Specification:
https://eips.ethereum.org/EIPS/eip-3668

PS: Please adjust the `component` this issue is tagged for if needed.

### Additional context

- [ethers-js](https://github.com/ethers-io/ethers.js/blob/6ee1a5f8bb38ec31fa84c00aae7f091e1d3d6837/lib.esm/providers/abstract-provider.d.ts#L287)
- [viem](https://github.com/wevm/viem/blob/e05147b24730b2f5b6df36566c333b5789b9eced/src/utils/ccip.ts#L110C28-L110C28)
- [ethers-rs-middleware](https://github.com/ensdomains/ethers-ccip-read)

**Comment by prestwich** [comment]
alloy policy is to implement provider extensions as downstream crates in separate repositories. We are happy to link to your implementation tho! please drop a link here :)

**Comment by ryanycw** [comment]
Hey team, I’m interested in helping with issue. Has any work been started or planned yet? If not, I’d love to get it moving forward :)

**Comment by stevedylandev** [comment]
Is it still safe to say there are no plans to implement this? Would an example of a ProviderExt be something like [this](https://github.com/sevenzing/alloy-ccip-read), or is there something else involved?

For context, ENS resolving these days involves a lot of CCIP calls so it would be either nice to have fully implemented or make it easier for alloy devs to find!

**Comment by mattsse** [comment]
@stevedylandev could you perhaps give #2584 a try and figure out what's missing for this and maybe take over this feature?

**Comment by stevedylandev** [comment]
Can definitely give it a shot!
