### ISSUE TITLE
[Feature] Add a method `status` in `ReceiptResponse` trait

### ISSUE THREAD

**Issue by moricho** [alloy-rs/alloy#845]
### Component

network, json-rpc

### Describe the feature you would like

It would be helpful to know the tx status from the receipt gotten by `get_receipt` method in `PendingTransactionBuilder` or by `get_transaction_receipt` in `Provider`.

(There might already be a way to understand the status from ReceiptResponse, but I couldn't find it.)

### Additional context

The solution of this issue would be like: https://github.com/alloy-rs/alloy/pull/846

**Comment by prestwich** [comment]
related to https://github.com/alloy-rs/alloy/issues/630

**Comment by moricho** [comment]
Closed by https://github.com/alloy-rs/alloy/pull/846
