### ISSUE TITLE
[Bug] ProviderBuilder with Hyper and Https

### ISSUE THREAD

**Issue by DaveWK** [alloy-rs/alloy#852]
### Component

provider, pubsub

### What version of Alloy are you on?

0.1.0

### Operating System

Linux

### Describe the bug

it seems that https does not work with the hyper feature at the moment. I see:
`Err(Transport(Custom(hyper_util::client::legacy::Error(Connect, \"invalid URL, scheme is not http\"))))`

when attempting to pass an https url to ProviderBuilder. This appears to be due to a nuisance with how hyper separates out the tls implementation by default.

My preference would be that alloy-rs enables a tls implementation for hyper by default to abstract this implementation detail, but would also be appreciative for some documentation on how to specify and enable the tls for the alloy-rs's hyper feature.

**Comment by HrikB** [comment]
I also get this issue when using reqwest. Http urls work fine but errors out on using https

**Comment by DaniPopes** [comment]
This has been enabled by default for some time, at least 0.2.0
