### ISSUE TITLE
[Feature] Add prelude export to `alloy` meta-crate

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/alloy#870]
### Component

alloy

### Describe the feature you would like

To define a `prelude::*` export

so that 

```rust
use alloy::{
    network::{EthereumSigner, TransactionBuilder},
    node_bindings::Anvil,
    primitives::U256,
    providers::{Provider, ProviderBuilder},
    rpc::types::TransactionRequest,
    signers::wallet::LocalWallet,
};
```

turns into

```rust
use alloy::prelude::*;
```

### Additional context

cc @gakonst

**Comment by prestwich** [comment]
I'm generally not in favor, as it makes supporting users harder

**Comment by prestwich** [comment]
per conversation elsewhere, none of the core maintainers seem in favor. closing as not planned
