### ISSUE TITLE
[Feature] Provide code to convert from alloy_primitives::Signature to alloy_rpc_types::Signature

### ISSUE THREAD

**Issue by ufoscout** [alloy-rs/alloy#890]
### Component

rpc

### Describe the feature you would like

The `rpc` crate provides code to convert from `alloy_rpc_types::Signature` to `alloy_primitives::Signature`; however, it is not clear how to perform the conversion in the opposite direction. Could you please provide an example to perform such a conversion or implement the try_from code directly in the `rpc` crate?

```rust
    let rpc_sig: alloy_rpc_types::Signature = ....;
    let primitives_sig = alloy_primitives::Signature::try_from(rpc_sig).unwrap();
    let rpc_sig2: alloy_rpc_types::Signature = ??? // <---- how to build it from primitives_sig?
```

**Comment by ufoscout** [comment]
Please, any help?

**Comment by mattsse** [comment]
closing this because we unified the types
