### ISSUE TITLE
[Feature] Add rpc types for eth_sendRawTransactionConditional

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#895]
### Component

rpc

### Describe the feature you would like

ref https://github.com/gakonst/ethers-rs/pull/2595

we should only add the types first, and then, since this endpoint is network specific, we probably should add an extension trait for the provider

**Comment by prestwich** [comment]
ERCs are generally out of scope for main repo. 4337 code should be a separate repo
