### ISSUE TITLE
[Feature] eth_simulateV1 Request / Response types

### ISSUE THREAD

**Issue by Rjected** [alloy-rs/alloy#901]
### Component

rpc

### Describe the feature you would like

`eth_simulateV1` (formerly `eth_multicallV1`) is an in-progress RPC endpoint that seems worth supporting in reth and alloy:
https://github.com/ethereum/execution-apis/pull/484

We first need some basic types to for serialization / deserialization. It looks like we will want some structures analogous to these geth structs:
https://github.com/s1na/go-ethereum/blob/4c325ba5b365e44f1c33cfe7b3236bcb685ec2de/internal/ethapi/simulate.go#L46-L59
https://github.com/s1na/go-ethereum/blob/4c325ba5b365e44f1c33cfe7b3236bcb685ec2de/internal/ethapi/simulate.go#L70-L75

for the simulate interface:
https://github.com/s1na/go-ethereum/blob/4c325ba5b365e44f1c33cfe7b3236bcb685ec2de/internal/ethapi/api.go#L1255

There seem to be many test vectors in the `execution-apis` PR, which should be useful

**Comment by JackG-eth** [comment]
Will take this

**Comment by DoTheBestToGetTheBest** [comment]
hey @JackG-eth are you always working on this ?

**Comment by JackG-eth** [comment]
> hey @JackG-eth are you always working on this ? 

Hey feel free to, having to feel with few life issues right now and haven't got time

**Comment by DoTheBestToGetTheBest** [comment]
> > hey @JackG-eth are you always working on this ?
> 
> Hey feel free to, having to feel with few life issues right now and haven't got time

no problem if you plan to work on it then i can take something else, GL!
