### ISSUE TITLE
[Feature] rpc::TransactionReceipt cant be reused for networks with different receipt types

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#904]
### Component

network, json-rpc

### Describe the feature you would like

Currently ReceiptResponse is implemented specifically for `TransactionReceipt` with default envelope type.
it can't be reused for other networks if the they have a different `T`.
I tried to add a blanket impl instead:

```rust
impl<T> ReceiptResponse for alloy_rpc_types_eth::TransactionReceipt<T>
where
    T: TxReceipt,
{
    fn contract_address(&self) -> Option<Address> {
        self.contract_address
    }

    fn status(&self) -> bool {
        TxReceipt::status(&self.inner)
    }
}

```

but this does not work because we can't constrain `TxReceipt<>`'s generic which is for logs.
I guess this can be solved by splitting TxReceipt into a non generic and a generic part that also has logs

```rust
trait<T> TxReceipt<T> : TxReceiptCore {}
```

or something like this.

**Comment by prestwich** [comment]
related:
https://github.com/alloy-rs/alloy/issues/623

**Comment by mattsse** [comment]
yeah this is a dup
