### ISSUE TITLE
[Feature] Add missing RPC namespaces and missing RPC methods

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/alloy#926]
### Component

rpc

### Describe the feature you would like

Achieve full compatibility with Reth's JSON-RPC methods and namespaces

Link: https://ethereum.org/en/developers/docs/apis/json-rpc/#json-rpc-methods

Missing namespaces:

- [x] [`rpc-types-web3`](https://reth.rs/jsonrpc/web3.html): https://github.com/alloy-rs/alloy/pull/996
- [x] [`rpc-types-net`](https://reth.rs/jsonrpc/net.html)
- [x] [`rpc-types-rpc`](https://reth.rs/jsonrpc/rpc.html)
- [x] [`rpc-types-mev`](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/mev.rs): https://github.com/paradigmxyz/reth/issues/9027)

Missing methods:

For [Trace](https://reth.rs/jsonrpc/trace.html):

- [x] trace_rawTransaction: #925
- [x] trace_replayBlockTransactions: #925
- [x] trace_filter: #946
- [x] trace_get: https://github.com/alloy-rs/alloy/pull/987

For [Admin](https://reth.rs/jsonrpc/admin.html):

- [x] admin_peerEvents_subscribe: https://github.com/alloy-rs/alloy/pull/991
- [x] ~~admin_peerEvents_unsubscribe~~

For [Debug](https://reth.rs/jsonrpc/debug.html):

- [x] debug_getRawHeader
- [x] debug_getRawBlock
- [x] debug_getRawTransaction
- [x] debug_getRawReceipts
- [x] debug_getBadBlocks
- [x] debug_traceChain
- [x] debug_traceBlock

**Comment by DaniPopes** [comment]
Yeah, sorry about that, I updated the remaining methods with their PR. Thanks to everyone!
