### ISSUE TITLE
[Feature] Use OtherFields for genesis extra_fields

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/alloy#932]
### Component

consensus, eips, genesis, serde

### Describe the feature you would like

use `Otherfields` for extra_fields

**Comment by DaniPopes** [comment]
This is just OtherFields

**Comment by mattsse** [comment]
ah now that otherfields is in alloy-serde we can replace this:

https://github.com/alloy-rs/alloy/blob/d94324bb9768ce8c15c4b0c207630d4c68cfd937/crates/genesis/src/lib.rs#L421-L424
