### ISSUE TITLE
[Bug] Some RPC methods don't expose BlockId

### ISSUE THREAD

**Issue by merklefruit** [alloy-rs/alloy#937]
### Component

provider, pubsub

### What version of Alloy are you on?

v0.1.1

### Operating System

macOS (Apple Silicon)

### Describe the bug

Some rpc methods are documented as also accepting a block height parameter, but they currently don't expose it.

Example: https://github.com/alloy-rs/alloy/blob/041c7c47b33907523cbe4023db03ae7bb57bf7bd/crates/provider/src/provider/trait.rs#L250-L254

This is the case for: get_account, get_balance, get_proof (as far as I can tell, I didn't check all other methods)

If you have a solution in mind I'm happy to open a PR for it

**Comment by mattsse** [comment]
this can be set via `RpcWithBlock::block_id`: https://docs.rs/alloy-provider/latest/alloy_provider/struct.RpcWithBlock.html#method.block_id
