### ISSUE TITLE
[Bug] When using a StateOverride with a CallBuilder to estimate_gas, the state overrides are not being applied

### ISSUE THREAD

**Issue by shankinson** [alloy-rs/alloy#968]
### Component

contract

### What version of Alloy are you on?

alloy v0.1.2

### Operating System

Linux

### Describe the bug

When trying to estimate gas with state overrides via a contract function call, the state overrides were not being applied.

Fixed in this PR: https://github.com/alloy-rs/alloy/pull/967

**Comment by zerosnacks** [comment]
Fixed in https://github.com/alloy-rs/alloy/pull/967
