### ISSUE TITLE
cargo check --target wasm32-unknown-unknown does not work on provider crate

### ISSUE THREAD

**Issue by Blaeaea** [alloy-rs/alloy#975]
### Component

provider, pubsub

### What version of Alloy are you on?

last git version

### Operating System

Other (please specify)

### Describe the bug

Hey guys i'am not able to check the provider crate, can you please tell me what i'am missing here?

The os i'am using is wsl2 on windows

**Comment by DaniPopes** [comment]
We don't support bare wasm for provider yet.

**Comment by Blaeaea** [comment]
> We don't support bare wasm for the provider crate and up yet.

how i'am supposed to compile the provider crate please?

**Comment by Blaeaea** [comment]
> We don't support bare wasm for the provider crate and up yet.

any idea pls?

**Comment by DaniPopes** [comment]
What do you want me to tell you? wasm32-unknown-unknown is not supported for all crates, use wasm32-wasi or another target
